### PR TITLE
sql-statement-alter-table: Beter example for schema dependency

### PR DESCRIPTION
**Pull request by dveeden**
### What is changed, added or deleted? (Required)

- The old example didn't have a table name, causing it to always return errors in both TiDB and MySQL.
- The old example didn't work in MySQL.

### Which TiDB version(s) do your changes apply to? (Required)

- [x] master (the latest development version)
- [x] v6.6 (TiDB 6.6 versions)
- [x] v6.5 (TiDB 6.5 versions)
- [ ] v6.4 (TiDB 6.4 versions)
- [x] v6.1 (TiDB 6.1 versions)
- [ ] v5.4 (TiDB 5.4 versions)
- [ ] v5.3 (TiDB 5.3 versions)
- [ ] v5.2 (TiDB 5.2 versions)
- [ ] v5.1 (TiDB 5.1 versions)
- [ ] v5.0 (TiDB 5.0 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s):

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

### CODE REVIEW

**Comment by dveeden** [comment]
The new example with TiDB:
```
sql> CREATE TABLE t(id INT PRIMARY KEY);
Query OK, 0 rows affected (0.0186 sec)

sql> ALTER TABLE t ADD COLUMN c1 INT, ADD COLUMN c2 INT AFTER c1;
ERROR: 1054 (42S22): Unknown column 'c1' in 't'
```

The new example with MySQL:
```
mysql [8.0.32] > CREATE TABLE t(id INT PRIMARY KEY);
Query OK, 0 rows affected (0.06 sec)

mysql [8.0.32] > ALTER TABLE t ADD COLUMN c1 INT, ADD COLUMN c2 INT AFTER c1;
Query OK, 0 rows affected (0.04 sec)
Records: 0  Duplicates: 0  Warnings: 0
```

The old example with TiDB:
```
sql> CREATE TABLE t(id INT PRIMARY KEY, i INT);
Query OK, 0 rows affected (0.0471 sec)

sql> ALTER TABLE ADD INDEX i(b), DROP INDEX i;
ERROR: 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use line 1 column 15 near "ADD INDEX i(b), DROP INDEX i" 

sql> ALTER TABLE t ADD INDEX i(b), DROP INDEX i;
ERROR: 1072 (42000): column does not exist: b
```

The old example with MySQL:
```
mysql [8.0.32] > CREATE TABLE t(id INT PRIMARY KEY, i INT);
Query OK, 0 rows affected (0.05 sec)

mysql [8.0.32] > ALTER TABLE ADD INDEX i(b), DROP INDEX i;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ADD INDEX i(b), DROP INDEX i' at line 1
mysql [8.0.32] > ALTER TABLE t ADD INDEX i(b), DROP INDEX i;
ERROR 1091 (42000): Can't DROP 'i'; check that column/key exists
```

**Comment by dveeden** [comment]
https://docs.pingcap.com/tidb/dev/mysql-compatibility#ddl also lists this issue, but with another correct example.

**Review by tangenta — APPROVED** [review]

**Review by TomShawn — APPROVED** [review]

**Comment by dveeden** [comment]
@benmaoer PTAL

**Review by benmaoer — APPROVED** [review]
LGTM

**Review by lilin90 — APPROVED** [review]
LGTM

**Pull request merged**
