### PR TITLE
tikv-control: Replace `--db` with `--data-dir`

### PR DESCRIPTION
**Pull request by dveeden**
### What is changed, added or deleted? (Required)

Required changes:

* Replace `--db` with `--data-dir`
* Remove `/db` from the path

```
[dvaneeden@dve-carbon tikv-0]$ tiup ctl:v5.2.2 tikv --db /home/dvaneeden/.tiup/data/SqRmWep/tikv-0/data/db size -r 2
Starting component `ctl`: /home/dvaneeden/.tiup/components/ctl/v5.2.2/ctl tikv --db /home/dvaneeden/.tiup/data/SqRmWep/tikv-0/data/db size -r 2
error: Invalid value for '--db <db>': DEPRECATED!!! Use --data-dir and --config instead
Error: exit status 1
Error: run `/home/dvaneeden/.tiup/components/ctl/v5.2.2/ctl` (wd:/home/dvaneeden/.tiup/data/SqWYNWa) failed: exit status 1
```

I used this:

```
sed -i -E 's/tikv-ctl (.*)--db ([^ ]*)\/db\/?/tikv-ctl \1--data-dir \2/g' tikv-control.md
```

### Which TiDB version(s) do your changes apply to? (Required)

- [x] master (the latest development version)
- [x] v5.3 (TiDB 5.3 versions)
- [x] v5.2 (TiDB 5.2 versions)
- [x] v5.1 (TiDB 5.1 versions)
- [ ] v5.0 (TiDB 5.0 versions)
- [ ] v4.0 (TiDB 4.0 versions)
- [ ] v3.1 (TiDB 3.1 versions)
- [ ] v3.0 (TiDB 3.0 versions)
- [ ] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

See also https://github.com/tikv/website/pull/307

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

### CODE REVIEW

**Comment by shichun-0415** [comment]
Hi, @dveeden. It seems the change needs to be synchronized to the docs-cn repo. Therefore, I changed the "translation no need" label to "translation/doing". FYI.

**Review by 5kbpers — APPROVED** [review]
Sorry for missing the review request so long, LGTM

**Review by TomShawn — APPROVED** [review]

**Pull request merged**
