### PR TITLE
Deleted tidb-lightning: max-error and duplicate-resolution

### PR DESCRIPTION
**Pull request by hfxsd**
### What is changed, added or deleted? (Required)

Deleted tidb-lightning: max-error and duplicate-resolution
This PR reverts https://github.com/pingcap/docs/pull/6717.

### Which TiDB version(s) do your changes apply to? (Required)

**Tips for choosing the affected version(s):**

By default, **CHOOSE MASTER ONLY** so your changes will be applied to the next TiDB major or minor releases. If your PR involves a product feature behavior change or a compatibility change, **CHOOSE THE AFFECTED RELEASE BRANCH(ES) AND MASTER**.

For details, see [tips for choosing the affected versions](https://github.com/pingcap/docs/blob/master/CONTRIBUTING.md#guideline-for-choosing-the-affected-versions).

- [x] master (the latest development version)
- [x] v5.3 (TiDB 5.3 versions)
- [ ] v5.2 (TiDB 5.2 versions)
- [ ] v5.1 (TiDB 5.1 versions)
- [ ] v5.0 (TiDB 5.0 versions)
- [ ] v4.0 (TiDB 4.0 versions)
- [ ] v3.1 (TiDB 3.1 versions)
- [ ] v3.0 (TiDB 3.0 versions)
- [ ] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s): https://github.com/pingcap/docs/pull/6717 https://github.com/pingcap/docs-cn/pull/7517

### Do your changes match any of the following descriptions?

- [x] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

### CODE REVIEW

**Review by sunzhaoyang — APPROVED** [review]

**Comment by TomShawn** [comment]
[This file](https://github.com/pingcap/docs/pull/6717/files#diff-e60eb511e8e7fcd107a7d3a7d3da20c1e422686d723c4f14446d0c05cb22c08bR66) also needs revert.

**Review by Liuxiaozhen12 — APPROVED** [review]

**Review by hfxsd — COMMENTED** [review]
LGTM

**Pull request merged**
