### PR TITLE
Fix typos in information-schemas

### PR DESCRIPTION
**Pull request by TomShawn**
### What is changed, added or deleted? (Required)
Fix typos in information-schemas introduced in https://github.com/pingcap/docs/pull/5062.

### Which TiDB version(s) do your changes apply to? (Required)

- [x] master (the latest development version)
- [x] v5.0 (TiDB 5.0 versions)
- [ ] v4.0 (TiDB 4.0 versions)
- [ ] v3.1 (TiDB 3.1 versions)
- [ ] v3.0 (TiDB 3.0 versions)
- [ ] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s):

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

### CODE REVIEW

**Comment by lilin90** [comment]
Please also help fix the similar typo in `information-schema/client-errors-summary-by-host.md`.

**Comment by TomShawn** [comment]
> Please also help fix the similar typo in `information-schema/client-errors-summary-by-host.md`.

Done in https://github.com/pingcap/docs/pull/5251/commits/5c4d7e016ef96477a7d03480a84a58f410fc5165.

**Review by yikeke — APPROVED** [review]

**Pull request merged**
