### PR TITLE
revert: cleanup sqlgram

### PR DESCRIPTION
**Pull request by Oreoxmt**
### What is changed, added or deleted? (Required)

Revert https://github.com/pingcap/docs/pull/16049.

After removing `media/sqlgram` from the master branch, docs in other branches that use the image from `media/sqlgram` fails to render. For example https://docs.pingcap.com/tidb/stable/sql-statement-use:

image

https://docs-archive.pingcap.com/tidb/v2.1/sql-statement-begin:
image

### Which TiDB version(s) do your changes apply to? (Required)

**Tips for choosing the affected version(s):**

By default, **CHOOSE MASTER ONLY** so your changes will be applied to the next TiDB major or minor releases. If your PR involves a product feature behavior change or a compatibility change, **CHOOSE THE AFFECTED RELEASE BRANCH(ES) AND MASTER**.

For details, see [tips for choosing the affected versions](https://github.com/pingcap/docs/blob/master/CONTRIBUTING.md#guideline-for-choosing-the-affected-versions).

- [x] master (the latest development version)
- [ ] v8.1 (TiDB 8.1 versions)
- [ ] v8.0 (TiDB 8.0 versions)
- [ ] v7.6 (TiDB 7.6 versions)
- [ ] v7.5 (TiDB 7.5 versions)
- [ ] v7.4 (TiDB 7.4 versions)
- [ ] v7.1 (TiDB 7.1 versions)
- [ ] v6.5 (TiDB 6.5 versions)
- [ ] v6.1 (TiDB 6.1 versions)
- [ ] v5.4 (TiDB 5.4 versions)
- [ ] v5.3 (TiDB 5.3 versions)
- [ ] v5.2 (TiDB 5.2 versions)
- [ ] v5.1 (TiDB 5.1 versions)
- [ ] v5.0 (TiDB 5.0 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s):

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

### CODE REVIEW

**Review by qiancai — APPROVED** [review]

**Review by dveeden — APPROVED** [review]
I assume this is a temporary solution?

**Comment by Oreoxmt** [comment]
@dveeden To optimize the storage and costs for our CDN while reusing images across multiple versions, we currently "merge" all images under `media/` across all branches and upload them to https://download.pingcap.com/images/docs/. This means we keep only one copy each image instead of one per branch. With 25 versions of TiDB docs in total, this approach saves significant storage space and costs. In most cases, we want to reuse images across versions to ensure consistency. Therefore, we cannot delete any images unless they are unused across all branches.

**Pull request merged**
