### PR TITLE
Update description of `tidb_replica_read` variable values for follower read

### PR DESCRIPTION
**Pull request by tommygood**
### First-time contributors' checklist 

- [x] I've signed [**Contributor License Agreement**](https://cla-assistant.io/pingcap/docs) that's required for repo owners to accept my contribution.

### What is changed, added or deleted? (Required)

- After reviewing the source code for client-go and TiDB, I noticed that some descriptions in the [follower read doc](https://docs.pingcap.com/tidb/stable/follower-read) do not fully align with the source code behavior and my test results.
1. Behavior of tidb_replica_read set to leader
    - According to [client-go](https://github.com/tikv/client-go/blob/master/internal/locate/replica_selector.go#L135), when `tidb_replica_read` is set to `leader`, if the leader replica's kv store is busy, which is partially determined by the [`tidb_load_based_replica_read_threshold`](https://docs.pingcap.com/tidb/stable/system-variables#tidb_load_based_replica_read_threshold-new-in-v700), then the client-go will select the others replica to read, which can be follower or learner replicas. 
    - I have updated the doc to reflect this behavior and clarify the relationship between `tidb_load_based_replica_read_threshold` and `tidb_replica_read` when set to `leader`.
2. Reading from Learner Replicas
    - Since reading from learner replicas is supported in the current version, I found it necessary to distinguish between reading from follower and learner replicas.
    -  There are generally no restrictions on reading from learner replicas when `tidb_replica_read` is set to `follower`, `leader-and-follower`, `prefer-leader`, or `closest-replicas`. However, the current documentation only mentions follower reads in these contexts.
    - More details on how replicas are chosen based on scores can be found in the [client-go calculateScore](https://github.com/tikv/client-go/blob/master/internal/locate/replica_selector.go#L386).
3. Behavior when tidb_replica_read is set to learner
    - [The doc](https://docs.pingcap.com/tidb/stable/follower-read#usage) currently states that :
        > When the value of `tidb_replica_read` is set to learner, TiDB reads data from the learner replica. If there is no learner replica in the Region, TiDB returns an error.

    - However, in my test results (under `v8.1.0`), when there are no learner replica and `tidb_replica_read` is set to `learner`, mysql client still can read data from tidb.This occurs because client-go will randomly choose the leader or follower replica to read. 
- Please let me know If I have misunderstood any concepts, Thanks !
### Which TiDB version(s) do your changes apply to? (Required)

**Tips for choosing the affected version(s):**

By default, **CHOOSE MASTER ONLY** so your changes will be applied to the next TiDB major or minor releases. If your PR involves a product feature behavior change or a compatibility change, **CHOOSE THE AFFECTED RELEASE BRANCH(ES) AND MASTER**.

For details, see [tips for choosing the affected versions](https://github.com/pingcap/docs/blob/master/CONTRIBUTING.md#guideline-for-choosing-the-affected-versions).

- [x] master (the latest development version)
- [ ] v8.4 (TiDB 8.4 versions)
- [ ] v8.3 (TiDB 8.3 versions)
- [ ] v8.2 (TiDB 8.2 versions)
- [ ] v8.1 (TiDB 8.1 versions)
- [ ] v8.0 (TiDB 8.0 versions)
- [ ] v7.5 (TiDB 7.5 versions)
- [ ] v7.1 (TiDB 7.1 versions)
- [ ] v6.5 (TiDB 6.5 versions)
- [ ] v6.1 (TiDB 6.1 versions)
- [ ] v5.4 (TiDB 5.4 versions)
- [ ] v5.3 (TiDB 5.3 versions)
- [ ] v5.2 (TiDB 5.2 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s):

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

### CODE REVIEW

**Comment by tommygood** [comment]
@cfzjywxk Would you mind reviewing this PR or assigning someone else to take a look? I would really appreciate your help. Thank you!

**Comment by cfzjywxk** [comment]
@tommygood 

Sorry for the late response, thanks for your feedback.

Some of the functional behavior descriptions mentioned above do indeed differ from the actual code implementation as you have mentioned in this PR. My thought is to separate the description of the functionality design from the error handling logic, as users are primarily concerned with the behavior of the functionality itself.

Error handling and retries are part of a more complex internal process (Ref: https://github.com/tikv/client-go/issues/1167) and may require a separate document for detailed explanation.

**Comment by tommygood** [comment]
Got it, thanks for your response.

**Pull request closed without merging**
