### PR TITLE
Added note about incompatibility between default collations in tidb a…

### PR DESCRIPTION
**Pull request by kolbe**
…nd mysql

### What is changed, added or deleted? (Required)

A user noticed that we have different default collations than MySQL (when using the "new framework for collations"). The result of this is that there are different behaviors between MySQL and TiDB in some cases. For example:

```
mysql> show character set like 'utf8%';
+---------+---------------+--------------------+--------+
| Charset | Description   | Default collation  | Maxlen |
+---------+---------------+--------------------+--------+
| utf8    |               | utf8_general_ci    |      3 |
| utf8mb4 | UTF-8 Unicode | utf8mb4_general_ci |      4 |
+---------+---------------+--------------------+--------+
2 rows in set (0.00 sec)

mysql> create database db1 default character set utf8 collate utf8_general_ci;
Query OK, 1 row affected (0.00 sec)

mysql> use db1
Database changed

mysql> CREATE TABLE tbl (col VARCHAR(100));
Query OK, 0 rows affected (0.02 sec)

mysql> CREATE TABLE db1.tbl2 (col VARCHAR(100)) charset utf8;
Query OK, 0 rows affected (0.01 sec)

mysql> CREATE TABLE db1.tbl3 (col VARCHAR(100)) collate 'utf8_general_ci' charset utf8;
Query OK, 0 rows affected (0.02 sec)

mysql> select table_name, table_collation from INFORMATION_SCHEMA.tables WHERE table_name like 'tbl%';
+------------+-----------------+
| table_name | table_collation |
+------------+-----------------+
| tbl        | utf8_general_ci |
| tbl2       | utf8_general_ci |
| tbl3       | utf8_general_ci |
+------------+-----------------+
3 rows in set (0.00 sec)
```

```
tidb> show character set like 'utf8%';
+---------+---------------+-------------------+--------+
| Charset | Description   | Default collation | Maxlen |
+---------+---------------+-------------------+--------+
| utf8    | UTF-8 Unicode | utf8_bin          |      3 |
| utf8mb4 | UTF-8 Unicode | utf8mb4_bin       |      4 |
+---------+---------------+-------------------+--------+
2 rows in set (0.00 sec)

tidb> create database db1 default character set utf8 collate utf8_general_ci;
Query OK, 0 rows affected (0.03 sec)

tidb> CREATE TABLE db1.tbl (col VARCHAR(100));
Query OK, 0 rows affected (0.04 sec)

tidb> CREATE TABLE db1.tbl3 (col VARCHAR(100)) collate 'utf8_general_ci' charset utf8;
Query OK, 0 rows affected (0.03 sec)

tidb> select table_name, table_collation from INFORMATION_SCHEMA.tables WHERE table_name like 'tbl%';
+------------+-----------------+
| table_name | table_collation |
+------------+-----------------+
| tbl        | utf8_general_ci |
| tbl2       | utf8_bin        |
| tbl3       | utf8_general_ci |
+------------+-----------------+
3 rows in set (0.01 sec)
```

### Which TiDB version(s) do your changes apply to? (Required)

- [x] master (the latest development version)
- [x] v4.0 (TiDB 4.0 versions)
- [ ] v3.1 (TiDB 3.1 versions)
- [ ] v3.0 (TiDB 3.0 versions)
- [ ] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s):

### CODE REVIEW

**Comment by TomShawn** [comment]
@kolbe Please specify the applicable version(s) of your change.

**Comment by kolbe** [comment]
I marked “master” and “v4.0”, what more do you want?

**Comment by TomShawn** [comment]
> I marked “master” and “v4.0”, what more do you want?
> […](#)
> On Jul 15, 2020, at 7:47 PM, TomShawn ***@***.***> wrote: ﻿ @kolbe Please specify the applicable version(s) of your change. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

Does your change also apply to v3.1/v3.0/v2.1? See the description in [v3.0](https://docs.pingcap.com/tidb/v3.0/character-set-and-collation)
image

**Comment by kolbe** [comment]
No, my clarification reflects the addition of the new framework for collations in v4.0.

**Pull request merged**
