### PR TITLE
Remove upgrade-tiflash.md

### PR DESCRIPTION
**Pull request by flowbehappy**
Duplicated with TiDB's upgrade manual.

### What is changed, added or deleted? (Required)

Remove upgrade-tiflash.md

### Which TiDB version(s) do your changes apply to? (Required)

- [x] master (the latest development version)
- [x] v4.0 (TiDB 4.0 versions)
- [ ] v3.1 (TiDB 3.1 versions)
- [ ] v3.0 (TiDB 3.0 versions)
- [ ] v2.1 (TiDB 2.1 versions)

**If you select two or more versions from above**, to trigger the bot to cherry-pick this PR to your desired release version branch(es), you **must** add corresponding labels such as **needs-cherry-pick-4.0**, **needs-cherry-pick-3.1**, **needs-cherry-pick-3.0**, and **needs-cherry-pick-2.1**.

### What is the related PR or file link(s)?

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/3164
- Other reference link(s):

### CODE REVIEW

**Comment by yikeke** [comment]
Do you need to add the TiFlash upgrade operations to TiDB's upgrade manual in this PR?

And please remove the link in TOC.md to fix CI.
@flowbehappy

**Comment by yikeke** [comment]
> Do you need to add the TiFlash upgrade operations to TiDB's upgrade manual in this PR?
> 
> And please remove the link in TOC.md to fix CI.
> @flowbehappy

Confirmed. No need.

**Comment by yikeke** [comment]
You can delete the dead link in TOC to pass CI. @flowbehappy

**Comment by zanmato1984** [comment]
Should pass lint when https://github.com/pingcap/docs/pull/2603 got merged.

**Pull request merged**
