### PR TITLE
README, dm: update the files that refer to "manually-handling-sharding-ddl-locks.md"

### PR DESCRIPTION
**Pull request by yikeke**
Because the original "troubleshooting-sharding-ddl-locks.md" has been renamed to "manually-handling-sharding-ddl-locks.md", I updated the README file and all the DM files that refer to this file. PTAL. @GregoryIan

### CODE REVIEW

**Comment by GregoryIan** [comment]
LGTM

**Comment by GregoryIan** [comment]
@csuzhangxc @lilin90 PTAL

**Comment by csuzhangxc** [comment]
1. whether needing to remove *troubleshooting-sharding-ddl-locks.md*?
2. DNM until #876 merged

**Comment by csuzhangxc** [comment]
rest LGTM

**Comment by lilin90** [comment]
All related changes are involved in #891, so I'll close this PR.

**Pull request closed without merging**
