### PR TITLE
Correct typo in Dumpling's GC auto extend feature spec

### PR DESCRIPTION
**Pull request by Tetsuya3850**
### What is changed, added or deleted? (Required)
I was reading the section regarding Dumpling's GC auto extension feature.
I understood that if data is less than 1 TB this feature works, but if larger it does not.
Given this, I thought the part that I changed could be a typo. Thus raised this fix.

Changed "more" to "less"

### Which TiDB version(s) do your changes apply to? (Required)

**Tips for choosing the affected version(s):**

By default, **CHOOSE MASTER ONLY** so your changes will be applied to the next TiDB major or minor releases. If your PR involves a product feature behavior change or a compatibility change, **CHOOSE THE AFFECTED RELEASE BRANCH(ES) AND MASTER**.

For details, see [tips for choosing the affected versions](https://github.com/pingcap/docs/blob/master/CONTRIBUTING.md#guideline-for-choosing-the-affected-versions).

- [x] master (the latest development version)
- [x] v7.6 (TiDB 7.6 versions)
- [x] v7.5 (TiDB 7.5 versions)
- [x] v7.4 (TiDB 7.4 versions)
- [ ] v7.3 (TiDB 7.3 versions)
- [x] v7.1 (TiDB 7.1 versions)
- [x] v6.5 (TiDB 6.5 versions)
- [ ] v6.1 (TiDB 6.1 versions)
- [ ] v5.4 (TiDB 5.4 versions)
- [ ] v5.3 (TiDB 5.3 versions)
- [ ] v5.2 (TiDB 5.2 versions)
- [ ] v5.1 (TiDB 5.1 versions)
- [ ] v5.0 (TiDB 5.0 versions)

### What is the related PR or file link(s)?
https://docs.pingcap.com/tidb/stable/dumpling-overview

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

### CODE REVIEW

**Comment by Tetsuya3850** [comment]
cc @qiancai 
Hi! Appreciate if you could please take a look at your convenience.

**Comment by Tetsuya3850** [comment]
@Icemap Hi! Much appreciated if you can please take a look at your convenience 🙇

**Comment by Icemap** [comment]
Hi @qiancai. I think @Tetsuya3850 had a great catch.

The expression is different between the [Chinese edition](https://docs.pingcap.com/zh/tidb/stable/dumpling-overview#%E6%89%8B%E5%8A%A8%E8%AE%BE%E7%BD%AE-tidb-gc-%E6%97%B6%E9%97%B4) and the [English edition](https://docs.pingcap.com/tidb/stable/dumpling-overview#manually-set-the-tidb-gc-time). And IMHO, the English version has some errors in it, but I'm not sure. PTAL.

image
image

**Comment by Tetsuya3850** [comment]
@Icemap Hi! Thank you for checking. Wondering if we can potentially get some more help here 🙇

**Review by qiancai — APPROVED** [review]

**Comment by qiancai** [comment]
Hi @Tetsuya3850, many thanks for the catch. The change looks good to me.  @Frank945946 Would you please take a look at this PR too? Thanks.

**Review by Frank945946 — APPROVED** [review]

**Pull request merged**
