### PR TITLE
MySQL Workbench: Added the alternative password placeholder on the Setup New Connection dialogue box

### PR DESCRIPTION
**Pull request by kenudeh**
…tup New Connection dialogue box

### First-time contributors' checklist 

- [x] I've signed [**Contributor License Agreement**](https://cla-assistant.io/pingcap/docs) that's required for repo owners to accept my contribution.

### What is changed, added or deleted? (Required)

I use MySQL Workbench version 8.034 on Windows. Instead of the "Store in Keychain" placeholder contained in the documentation, I had "Store in Vault" on the Setup New Connection dialogue box. This pull request is to prevent confusion for users who may not see "Store in Keychain" when trying to connect to TiDB through MySQL Workbench.

### Which TiDB version(s) do your changes apply to? (Required)

**Tips for choosing the affected version(s):**

By default, **CHOOSE MASTER ONLY** so your changes will be applied to the next TiDB major or minor releases. If your PR involves a product feature behavior change or a compatibility change, **CHOOSE THE AFFECTED RELEASE BRANCH(ES) AND MASTER**.

For details, see [tips for choosing the affected versions](https://github.com/pingcap/docs/blob/master/CONTRIBUTING.md#guideline-for-choosing-the-affected-versions).

- [x] master (the latest development version)
- [ ] v7.6 (TiDB 7.6 versions)
- [ ] v7.5 (TiDB 7.5 versions)
- [ ] v7.4 (TiDB 7.4 versions)
- [ ] v7.3 (TiDB 7.3 versions)
- [ ] v7.1 (TiDB 7.1 versions)
- [ ] v6.5 (TiDB 6.5 versions)
- [ ] v6.1 (TiDB 6.1 versions)
- [ ] v5.4 (TiDB 5.4 versions)
- [ ] v5.3 (TiDB 5.3 versions)
- [ ] v5.2 (TiDB 5.2 versions)
- [ ] v5.1 (TiDB 5.1 versions)
- [ ] v5.0 (TiDB 5.0 versions)

### What is the related PR or file link(s)?

https://docs.pingcap.com/tidbcloud/dev-guide-gui-mysql-workbench

- This PR is translated from:
- Other reference link(s):

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

### CODE REVIEW

**Comment by kenudeh** [comment]
I meant MySQL Workbench version 8.0.34 Community Edition.

**Review by dveeden — APPROVED** [review]
MySQL Workbench 8.0.34 on Linux has `Store in Keychain ...`.

Looks like the logic for this is this:
https://github.com/mysql/mysql-workbench/blob/6e135fb33942123c57f059139cbd787bea4f3f9b/backend/wbpublic/grtui/grtdb_connect_panel.cpp#L1044-L1050

So on Windows it is "Vault" and other platforms have "Keychain".

**Review by Icemap — APPROVED** [review]
LGTM

**Review by qiancai — APPROVED** [review]

**Pull request merged**
