### PR TITLE
placement: Update placement-rules-in-sql.md

### PR DESCRIPTION
**Pull request by lcwangchao**
### First-time contributors' checklist 

- [x] I've signed [**Contributor License Agreement**](https://cla-assistant.io/pingcap/docs) that's required for repo owners to accept my contribution.

### Which TiDB version(s) do your changes apply to? (Required)

**Tips for choosing the affected version(s):**

By default, **CHOOSE MASTER ONLY** so your changes will be applied to the next TiDB major or minor releases. If your PR involves a product feature behavior change or a compatibility change, **CHOOSE THE AFFECTED RELEASE BRANCH(ES) AND MASTER**.

For details, see [tips for choosing the affected versions](https://github.com/pingcap/docs/blob/master/CONTRIBUTING.md#guideline-for-choosing-the-affected-versions).

- [ ] master (the latest development version)
- [x] v5.4 (TiDB 5.4 versions)
- [x] v5.3 (TiDB 5.3 versions)
- [ ] v5.2 (TiDB 5.2 versions)
- [ ] v5.1 (TiDB 5.1 versions)
- [ ] v5.0 (TiDB 5.0 versions)
- [ ] v4.0 (TiDB 4.0 versions)
- [ ] v3.1 (TiDB 3.1 versions)
- [ ] v3.0 (TiDB 3.0 versions)
- [ ] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

- docs-cn PR: https://github.com/pingcap/docs-cn/pull/8147
- Other reference link(s):

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

### CODE REVIEW

**Review by xhebox — APPROVED** [review]
LGTM

**Comment by morgo** [comment]
@lcwangchao The referenced issue is now closed. Does that mean it affects 5.4 and below but not master?

**Comment by lcwangchao** [comment]
> @lcwangchao The referenced issue is now closed. Does that mean it affects 5.4 and below but not master?

Yes. That issue is only fixed in master，I've unchecked the master

**Comment by lcwangchao** [comment]
> @lcwangchao The referenced issue is now closed. Does that mean it affects 5.4 and below but not master?

Yes. That issue is only fixed in master，I've unchecked the master

**Comment by TomShawn** [comment]
> > @lcwangchao The referenced issue is now closed. Does that mean it affects 5.4 and below but not master?
> 
> Yes. That issue is only fixed in master，I've unchecked the master

If this PR does not apply to master, please rebase this PR from master to release-5.3. Thanks~

**Pull request closed without merging**
