### PR TITLE
*: fix many typos

### PR DESCRIPTION
**Pull request by xiekeyi98**
Signed-off-by: keyixie <keyixie@tencent.com>

### What is changed, added or deleted? 
1. Fix Many misspells.
By the way : someone may not a misspell , just a difference with American and England .

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/docs/1603)

### CODE REVIEW

**Comment by lilin90** [comment]
@xiekeyi98 Sharp eyes~ Thanks a lot for improving docs!

**Comment by xiekeyi98** [comment]
> @xiekeyi98 Sharp eyes~ Thanks a lot for improving docs!

@lilin90  Not me, just many great tools to help me make our docs pretty.

nitpicking，I think we could use some checks for this repo.
Emmm , Like CI in the tidb.

Here may have some great tools for us.
image

**Comment by lilin90** [comment]
@xiekeyi98 Good idea! Currently, we use some extensions in VS Code to help check spelling errors, but we cannot guarantee no PR has typos. Adding ti to CI check would be better. 

@yikeke Could you please help follow up this? Thanks!

**Comment by xiekeyi98** [comment]
> > @xiekeyi98 Good idea! Currently, we use some extensions in VS Code to help check spelling errors, but we cannot guarantee no PR has typos. Adding ti to CI check would be better.
> > @yikeke Could you please help follow up this? Thanks!
> 
> Sure, I‘ll look for a tool and integrate the misspelling check into our docs/docs-cn repo. @lilin90
> 
> Thanks for the advice! @xiekeyi98

Here are some gossip for me .
We should be careful for some spell like nickname or slang.
For example, Misspell tool tells me it is a misspell , indeed, it just a nickname.
Luckly, many tools can ignore some pattern.
And we may need the developer to help us make a shell or script.
image

**Pull request merged**
