### PR TITLE
br, cdc: remove cdclog sink and PiTR

### PR DESCRIPTION
**Pull request by YuJuncen**
### First-time contributors' checklist 

- [x] I've signed [**Contributor License Agreement**](https://cla-assistant.io/pingcap/docs) that's required for repo owners to accept my contribution.

### What is changed, added or deleted? (Required)

According to @IANTHEREAL, the cdclog sink and the PiTR are just prototype features(even not experimental) and not ready to be documented. They should be removed for preventing misusing of them.

### Which TiDB version(s) do your changes apply to? (Required)

- [x] master (the latest development version)
- [x] v5.1 (TiDB 5.1 versions)
- [x] v5.0 (TiDB 5.0 versions)
- [ ] v4.0 (TiDB 4.0 versions)
- [ ] v3.1 (TiDB 3.1 versions)
- [ ] v3.0 (TiDB 3.0 versions)
- [ ] v2.1 (TiDB 2.1 versions)

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

### CODE REVIEW

**Comment by dveeden** [comment]
I don't think removing the docs is the right step. If this is not production ready people should be warned about that.

Would be better to either:
- put a warning about this being very experimental and far from production ready into the docs
- put the feature behind a (compile time?) feature flag that is disabled for production builds
- remove the code and put it into a different branch or something similar
- Make the code production ready, maybe with a very reduced scope etc.

**Comment by IANTHEREAL** [comment]
It is always not easy to delete existing content. I have also tried to delete these content. The essence is that this feature is completely a prototype demo. It is irresponsible for any user to use or test

**Comment by IANTHEREAL** [comment]
I think we can move the code to another branch and delete it from the master branch. Then we can keep the document in a single document or delete them, how about it?  @YuJuncen @dveeden

**Comment by dveeden** [comment]
@IANTHEREAL yes that sounds good to me

**Comment by kolbe** [comment]
> I think we can move the code to another branch and delete it from the master branch. Then we can keep the document in a single document or delete them, how about it? @YuJuncen @dveeden

I'm glad to see that there's a plan to move the code elsewhere. It would be one thing if it were only in the master branch, but the fact it is also included in "GA" releases is really a very big problem.

**Comment by dveeden** [comment]
@IANTHEREAL @YuJuncen What is the plan with this PR?

**Comment by YuJuncen** [comment]
@dveeden @db-will has discussed with @IANTHEREAL, we decided to keep this document, marked them as 'experimental feature' (#6565).

Eh, BTW, if possible, please @IANTHEREAL take a look and make sure we can keep the document then. I will change the PR to fit the requirement of #6565 firstly.

**Comment by dveeden** [comment]
@IANTHEREAL @3pointer can we make this ready to be merged?

**Comment by dveeden** [comment]
@IANTHEREAL @3pointer @TomShawn Now that https://github.com/pingcap/tiflow/pull/3599 is merged this should be removed isn't it?

**Comment by shichun-0415** [comment]
Fixed in https://github.com/pingcap/docs/pull/7500.

**Pull request closed without merging**
