### PR TITLE
basic-features: collapse charset and collations

### PR DESCRIPTION
**Pull request by morgo**
### What is changed, added or deleted? (Required)

It looks a bit strange on https://docs.pingcap.com/tidb/dev/basic-features because you have to scroll for quite a while until there is something different between versions. This will probably always be the case given the very quick release-cycle.

As a partial fix, this collapses charset and collations to take up less screen realestate.

### Which TiDB version(s) do your changes apply to? (Required)

**Tips for choosing the affected version(s):**

By default, **CHOOSE MASTER ONLY** so your changes will be applied to the next TiDB major or minor releases. If your PR involves a product feature behavior change or a compatibility change, **CHOOSE THE AFFECTED RELEASE BRANCH(ES) AND MASTER**.

For details, see [tips for choosing the affected versions](https://github.com/pingcap/docs/blob/master/CONTRIBUTING.md#guideline-for-choosing-the-affected-versions).

- [x] master (the latest development version)
- [x] v5.2 (TiDB 5.2 versions)
- [x] v5.1 (TiDB 5.1 versions)
- [x] v5.0 (TiDB 5.0 versions)
- [ ] v4.0 (TiDB 4.0 versions)
- [ ] v3.1 (TiDB 3.1 versions)
- [ ] v3.0 (TiDB 3.0 versions)
- [ ] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s):

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

### CODE REVIEW

**Comment by TomShawn** [comment]
@morgo Need to delete Line 132 as well? https://github.com/pingcap/docs/pull/6452/files#diff-f57b03d95a0d7cafe551282b68afefecc0144e070a5f9817f69890be229c691eR132

**Comment by morgo** [comment]
> @morgo Need to delete Line 132 as well? https://github.com/pingcap/docs/pull/6452/files#diff-f57b03d95a0d7cafe551282b68afefecc0144e070a5f9817f69890be229c691eR132

No, it's still used on L30

**Review by TomShawn — APPROVED** [review]
LGTM

**Pull request merged**
