### PR TITLE
mysql-compatibility: Add GROUP BY implicit order

### PR DESCRIPTION
**Pull request by morgo**
### First-time contributors' checklist 

- [x] I've signed [**Contributor License Agreement**](https://cla-assistant.io/pingcap/docs) that's required for repo owners to accept my contribution.

### What is changed, added or deleted? (Required)

TiDB differs from MySQL in a way that might impact migrations. Here is a testcase to prove it:

```sql
DROP TABLE IF EXISTS t1;
CREATE TABLE t1 (
    id INT NOT NULL PRIMARY KEY auto_increment,
    b INT NOT NULL
);
INSERT INTO t1 (b) VALUES (1),(2),(2),(3),(1),(4);
SELECT b, COUNT(*) FROM t1 GROUP BY b;

TiDB:

tidb> SELECT b, COUNT(*) FROM t1 GROUP BY b;
+---+----------+
| b | COUNT(*) |
+---+----------+
| 3 |        1 |
| 2 |        2 |
| 4 |        1 |
| 1 |        2 |
+---+----------+
4 rows in set (0.00 sec)

MySQL:

mysql [localhost:5731] {msandbox} (test) > SELECT b, COUNT(*) FROM t1 GROUP BY b;
+---+----------+
| b | COUNT(*) |
+---+----------+
| 1 |        2 |
| 2 |        2 |
| 3 |        1 |
| 4 |        1 |
+---+----------+
4 rows in set (0.00 sec)

Note the difference in plan showing this is intentionally sorted:

mysql [localhost:5731] {msandbox} (test) > explain SELECT b, COUNT(*) FROM t1 GROUP BY b;
+----+-------------+-------+------------+------+---------------+------+---------+------+------+----------+---------------------------------+
| id | select_type | table | partitions | type | possible_keys | key  | key_len | ref  | rows | filtered | Extra                           |
+----+-------------+-------+------------+------+---------------+------+---------+------+------+----------+---------------------------------+
|  1 | SIMPLE      | t1    | NULL       | ALL  | NULL          | NULL | NULL    | NULL |    6 |   100.00 | Using temporary; Using filesort |
+----+-------------+-------+------------+------+---------------+------+---------+------+------+----------+---------------------------------+
1 row in set, 1 warning (0.00 sec)

mysql [localhost:5731] {msandbox} (test) > explain SELECT b, COUNT(*) FROM t1 GROUP BY b ORDER BY NULL;
+----+-------------+-------+------------+------+---------------+------+---------+------+------+----------+-----------------+
| id | select_type | table | partitions | type | possible_keys | key  | key_len | ref  | rows | filtered | Extra           |
+----+-------------+-------+------------+------+---------------+------+---------+------+------+----------+-----------------+
|  1 | SIMPLE      | t1    | NULL       | ALL  | NULL          | NULL | NULL    | NULL |    6 |   100.00 | Using temporary |
+----+-------------+-------+------------+------+---------------+------+---------+------+------+----------+-----------------+
1 row in set, 1 warning (0.00 sec)

```

### Which TiDB version(s) do your changes apply to? (Required)

- [x] master (the latest development version)
- [x] v4.0 (TiDB 4.0 versions)
- [x] v3.1 (TiDB 3.1 versions)
- [x] v3.0 (TiDB 3.0 versions)
- [x] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s):

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

### CODE REVIEW

**Comment by morgo** [comment]
PTAL @zz-jason

**Review by kolbe — APPROVED** [review]
LGTM

**Pull request merged**
