### PR TITLE
fix comment syntax for correct website rendering

### PR DESCRIPTION
**Pull request by hongshaoyang**
### First-time contributors' checklist 

- [X] I've signed [**Contributor License Agreement**](https://cla-assistant.io/pingcap/docs) that's required for repo owners to accept my contribution.

### What is changed, added or deleted? (Required)

TiDB docs website docs.pingcap.com does not support "#" as a comment. It shows as SQL code, which confuses readers:

image

### Which TiDB version(s) do your changes apply to? (Required)

**Tips for choosing the affected version(s):**

By default, **CHOOSE MASTER ONLY** so your changes will be applied to the next TiDB major or minor releases. If your PR involves a product feature behavior change or a compatibility change, **CHOOSE THE AFFECTED RELEASE BRANCH(ES) AND MASTER**.

For details, see [tips for choosing the affected versions](https://github.com/pingcap/docs/blob/master/CONTRIBUTING.md#guideline-for-choosing-the-affected-versions).

- [X] master (the latest development version)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s):

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

### CODE REVIEW

**Review by Oreoxmt — APPROVED** [review]

**Comment by Oreoxmt** [comment]
@hongshaoyang Thanks for your contribution! Since TiDB supports using "#" or "--" to comment a line, could you please describe the reason for creating this PR?

**Comment by hongshaoyang** [comment]
> @hongshaoyang Thanks for your contribution! Since TiDB supports using "#" or "--" to comment a line, could you please describe the reason for creating this PR?

TiDB docs website docs.pingcap.com does not support "#" as a comment. It shows as SQL code, which confuses readers. 
Screenshot 2024-04-01 at 5 55 22 PM

**Review by hfxsd — APPROVED** [review]

**Pull request merged**
