### PR TITLE
Add async commit configuration

### PR DESCRIPTION
**Pull request by Joyinqin**
### What is changed, added or deleted? (Required)
Add Async Commit feature.

### Which TiDB version(s) do your changes apply to? (Required)

- [x] master (the latest development version)
- [ ] v4.0 (TiDB 4.0 versions)
- [ ] v3.1 (TiDB 3.1 versions)
- [ ] v3.0 (TiDB 3.0 versions)
- [ ] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/4527 https://github.com/pingcap/docs-cn/pull/4779
- Other reference link(s):

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Have version specific changes 
- [ ] Might cause conflicts

### CODE REVIEW

**Comment by sticnarf** [comment]
Sorry but the documentation is stale now due to the rapid development on the master branch. And it is expected to have some other changes in this section soon. Can we wait until the changes on TiDB and docs-cn are landed?

**Comment by TomShawn** [comment]
> Sorry but the documentation is stale now due to the rapid development on the master branch. And it is expected to have some other changes in this section soon. Can we wait until the changes on TiDB and docs-cn are landed?

Thanks for reminding!

**Comment by TomShawn** [comment]
> Sorry but the documentation is stale now due to the rapid development on the master branch. And it is expected to have some other changes in this section soon. Can we wait until the changes on TiDB and docs-cn are landed?

Any update?

**Comment by TomShawn** [comment]
@Joyinqin The follow-up docs-cn PR is https://github.com/pingcap/docs-cn/pull/4779. Once it is merged, please help translate it here, thanks!

**Comment by Joyinqin** [comment]
@TomShawn Get it~

**Comment by Joyinqin** [comment]
I will reopen a pr for the git error operation.

**Comment by Joyinqin** [comment]
I will reopen a pr for the git error operation.

**Pull request closed without merging**
