### PR TITLE
tikv: fix wrong description and default value for enable-statistics

### PR DESCRIPTION
**Pull request by tabokie**
Signed-off-by: tabokie <xy.tao@outlook.com>

### First-time contributors' checklist 

- [x] I've signed [**Contributor License Agreement**](https://cla-assistant.io/pingcap/docs) that's required for repo owners to accept my contribution.

### What is changed, added or deleted? (Required)

Fix wrong description and default value for enable-statistics.

### Which TiDB version(s) do your changes apply to? (Required)

- [x] master (the latest development version)
- [x] v4.0 (TiDB 4.0 versions)
- [x] v3.1 (TiDB 3.1 versions)
- [x] v3.0 (TiDB 3.0 versions)
- [x] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

default enabled since [release-1.0](https://github.com/tikv/tikv/blob/release-1.0/etc/config-template.toml)

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

### CODE REVIEW

**Comment by TomShawn** [comment]
Could you involve a technical review?

**Comment by tabokie** [comment]
@yiwu-arbug

**Review by yiwu-arbug — COMMENTED** [review]
LGTM

**Review by TomShawn — APPROVED** [review]

**Pull request merged**
