### PR TITLE
Improve images of three dcs in 2 cities

### PR DESCRIPTION
**Pull request by TomShawn**
### What is changed, added or deleted? (Required)

Improve images of three dcs in 2 cities:
- Replace "Beijing" with "Seattle"
- Replace "Xi'an" with "San Francisco"
- Improve the display

### Which TiDB version(s) do your changes apply to? (Required)

- [x] master (the latest development version)
- [x] v4.0 (TiDB 4.0 versions)
- [ ] v3.1 (TiDB 3.1 versions)
- [ ] v3.0 (TiDB 3.0 versions)
- [ ] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s):

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Have version specific changes 
- [ ] Might cause conflicts

### CODE REVIEW

**Review by lilin90 — COMMENTED** [review]
It should be "TiDB2 + PD2" in the `three-data-centers-in-two-cities-deployment-02.png` image. image

**Comment by lilin90** [comment]
Would you please also involve a tech reviewer?

**Comment by TomShawn** [comment]
@freyfl Could you help take a loot at the redrawn images? Thanks!

**Comment by TomShawn** [comment]
> Would you please also involve a tech reviewer?



> It should be "TiDB2 + PD2" in the `three-data-centers-in-two-cities-deployment-02.png` image. image

Fixed in https://github.com/pingcap/docs/pull/4025/commits/b0f5791e771d14b128b32550533115a315ed504f.
image

**Comment by freyfl** [comment]
LGTM

**Review by freyfl — APPROVED** [review]
LGTM

**Review by lilin90 — APPROVED** [review]
LGTM

**Pull request merged**
