### PR TITLE
partitioning: change formatting

### PR DESCRIPTION
**Pull request by dveeden**
### What is changed, added or deleted? (Required)

- Uppercase function names
- Add `()` to indicate it is a function
- Add link to docs

### Which TiDB version(s) do your changes apply to? (Required)

- [x] master (the latest development version)
- [x] v6.6 (TiDB 6.6 versions)
- [x] v6.5 (TiDB 6.5 versions)
- [x] v6.4 (TiDB 6.4 versions)
- [x] v6.1 (TiDB 6.1 versions)
- [ ] v5.4 (TiDB 5.4 versions)
- [ ] v5.3 (TiDB 5.3 versions)
- [ ] v5.2 (TiDB 5.2 versions)
- [ ] v5.1 (TiDB 5.1 versions)
- [ ] v5.0 (TiDB 5.0 versions)

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

### CODE REVIEW

**Comment by dveeden** [comment]
https://github.com/pingcap/tidb/blob/cb5affbc3cced5e75232c1cd8804431bad5ea5d6/planner/core/rule_partition_processor.go#L1263-L1273

Looks like `YEAR()` might need to be added to this list.

**Review by mjonss — APPROVED** [review]

**Comment by dveeden** [comment]
> https://github.com/pingcap/tidb/blob/cb5affbc3cced5e75232c1cd8804431bad5ea5d6/planner/core/rule_partition_processor.go#L1263-L1273
> 
> Looks like `YEAR()` might need to be added to this list.

@mjonss should we add `YEAR()` or not?

**Review by wshwsh12 — APPROVED** [review]

**Review by shichun-0415 — APPROVED** [review]
Rest LGTM

**Pull request merged**
