### PR TITLE
dev, v2.1, v3.0: update the sysbench link

### PR DESCRIPTION
**Pull request by CaitinChen**
### What is changed, added or deleted? 

Update the sysbench link.

### What is the related PR or file link(s)? 

docs-cn:
- https://github.com/pingcap/docs-cn/pull/1504
- https://github.com/pingcap/docs-cn/pull/1499

docs: https://github.com/pingcap/docs/pull/1279

### Which version does your change affect? 

dev, v2.1, v3.0

@lilin90 PTAL

### CODE REVIEW

**Comment by morgo** [comment]
I think it is better to use relative links here to the manual pages (vs. linking to GitHub). It should be better for SEO to drive everything to pingcap.com, plus redirects will work as files change.

**Comment by CaitinChen** [comment]
@morgo Currently, we only maintain sysbench files on GitHub, so users can obtain more information if we use absolute links here.

**Comment by CaitinChen** [comment]
@lilin90 @jackysp PTAL

**Comment by CaitinChen** [comment]
@jackysp PTAL again.

**Pull request merged**
