### PR TITLE
Clarify telemetry on Dashboard

### PR DESCRIPTION
**Pull request by cncc**
To clarify, you can't enable/disable telemetry on Dashboard

### First-time contributors' checklist 

- [ ] I've signed [**Contributor License Agreement**](https://cla-assistant.io/pingcap/docs) that's required for repo owners to accept my contribution.

### What is changed, added or deleted? (Required)

To clarify that, you can't enable/disable telemetry from dashboard now.

### Which TiDB version(s) do your changes apply to? (Required)

- [x] master (the latest development version)
- [x] v5.0 (TiDB 5.0 versions)
- [x] v4.0 (TiDB 4.0 versions)
- [ ] v3.1 (TiDB 3.1 versions)
- [ ] v3.0 (TiDB 3.0 versions)
- [ ] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

- This PR is translated from: It will be great if all Chinese/EN documentation could be updated.
- Other reference link(s):https://docs.pingcap.com/zh/tidb/stable/telemetry

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

### CODE REVIEW

**Comment by breeswish** [comment]
I think the understanding is incorrect. This configuration is a configuration for TiDB Dashboard, not for TiDB. It's just not a UI.

**Comment by TomShawn** [comment]
@breeswish PTAL again. Thanks!

**Review by breeswish — APPROVED** [review]
Thanks!

**Pull request merged**
