### PR TITLE
Fix broken link in error codes doc and support doc

### LINKED ISSUE #6194: Broken links
## Error Report

```sh
#!/bin/sh

http_status_ok="0,200,400,403,429,999"

find . -type f -name "*\.md" -exec /usr/local/bin/markdown-link-check -q -a $http_status_ok {} \; 2> /dev/null | awk '
/^FILE/ {
  file=$2
}

/→ Status: / {
  print file " - " $2 " → Status: " $NF
}
'
```

Result:
```
./tiup/tiup-dm-topology-reference.md - https://github.com/pingcap/tiup/blob/master/embed/templates/examples/dm/topology.example.yaml → Status: 404
./tiup/tiup-cluster.md - https://github.com/pingcap/tiup/blob/master/embed/templates/examples/topology.example.yaml → Status: 404
./tiup/tiup-cluster-topology-reference.md - https://github.com/pingcap/tiup/blob/master/embed/templates/examples/topology.example.yaml → Status: 404
./error-codes.md - https://dev.mysql.com/doc/refman/5.7/en/server-error-reference.html → Status: 404
./maintain-tidb-using-tiup.md - https://github.com/pingcap/tiup/blob/master/embed/templates/examples/topology.example.yaml → Status: 404
./support.md - https://pingcap.com/tidbslack → Status: 404
./production-deployment-using-tiup.md - https://github.com/pingcap/tiup/blob/master/embed/templates/examples/topology.example.yaml → Status: 404
./production-deployment-using-tiup.md - https://github.com/pingcap/tiup/blob/master/embed/templates/examples/topology.example.yaml#L7 → Status: 404
```
This is excluding what was reported in #6192 and #6193

### PR DESCRIPTION
**Pull request by dveeden**
### What is changed, added or deleted? (Required)

Fix a broken link

Alternative targets:

- https://dev.mysql.com/doc/mysql-errors/5.7/en/server-error-reference.html
- https://dev.mysql.com/doc/mysql-errors/8.0/en/

### Which TiDB version(s) do your changes apply to? (Required)

- [x] master (the latest development version)
- [x] v5.1 (TiDB 5.1 versions)
- [x] v5.0 (TiDB 5.0 versions)
- [x] v4.0 (TiDB 4.0 versions)
- [ ] v3.1 (TiDB 3.1 versions)
- [ ] v3.0 (TiDB 3.0 versions)
- [ ] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

Closes #6194 

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

### CODE REVIEW

**Review by tisonkun — APPROVED** [review]
Thanks for your contribution @dveeden ! LGTM.

**Review by TomShawn — APPROVED** [review]
LGTM

**Comment by TomShawn** [comment]
@dveeden Thanks!

**Pull request merged**
