### PR TITLE
fix-broken-external-links

### PR DESCRIPTION
**Pull request by en-jin19**
### What is changed, added or deleted? (Required)

- fixed some broken external links

### Which TiDB version(s) do your changes apply to? (Required)

- [x] master (the latest development version)
- [x] v5.1 (TiDB 5.1 versions)
- [x] v5.0 (TiDB 5.0 versions)
- [x] v4.0 (TiDB 4.0 versions)
- [x] v3.1 (TiDB 3.1 versions)
- [x] v3.0 (TiDB 3.0 versions)
- [x] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s): https://github.com/pingcap/docs-cn/pull/6626

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

### CODE REVIEW

**Comment by en-jin19** [comment]
I've finished the self-check of this PR. PTAL @TomShawn

**Comment by TomShawn** [comment]
@en-jin19 Good job! There are still two things to improve:
+ Add the `translation/from-docs-cn` label to indicate that this PR is translated from a docs-cn PR.
+ This PR is based on the master branch, so the `needs-cherry-pick-master` label is not needed.

**Review by TomShawn — APPROVED** [review]
LGTM

**Pull request merged**
