### PR TITLE
mysql-compatibility: Document LOAD DATA compatibility

### PR DESCRIPTION
**Pull request by dveeden**
### What is changed, added or deleted? (Required)

Added information about `LOAD DATA...REPLACE` compatibility.

### Which TiDB version(s) do your changes apply to? (Required)

- [x] master (the latest development version)
- [x] v5.0 (TiDB 5.0 versions)
- [ ] v4.0 (TiDB 4.0 versions)
- [ ] v3.1 (TiDB 3.1 versions)
- [ ] v3.0 (TiDB 3.0 versions)
- [ ] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

- Other reference link(s): https://github.com/pingcap/tidb/issues/24515

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

### CODE REVIEW

**Comment by dveeden** [comment]
Looking at [the code](https://github.com/pingcap/tidb/blob/master/executor/load_data.go) there seem to be two other cases we don't support yet
```
$ grep TODO executor/load_data.go
	// TODO: support load data without local field.
	// TODO: support load data with replace field.
	// TODO: support lines terminated is "".
```

**Review by TomShawn — APPROVED** [review]
LGTM

**Pull request merged**
