### PR TITLE
config: update default value of `max-txn-ttl`

### PR DESCRIPTION
**Pull request by jackysp**
Signed-off-by: Shuaipeng Yu <jackysp@gmail.com>

### First-time contributors' checklist 

- [X] I've signed [**Contributor License Agreement**](https://cla-assistant.io/pingcap/docs) that's required for repo owners to accept my contribution.

### Which TiDB version(s) do your changes apply to? (Required)

- [X] master (the latest development version)
- [X] v5.0 (TiDB 5.0 versions)
- [ ] v4.0 (TiDB 4.0 versions)
- [ ] v3.1 (TiDB 3.1 versions)
- [ ] v3.0 (TiDB 3.0 versions)
- [ ] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s):

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

### CODE REVIEW

**Comment by jackysp** [comment]
external-link-check failed.

**Comment by bb7133** [comment]
/uncc bb7133 I'm not a reviewer :)

**Comment by bb7133** [comment]
But I'll still say 'LGTM'.

**Comment by TomShawn** [comment]
> external-link-check failed.

There's nothing wrong with this PR. The failure does not affect the merge, so we can just ignore it.

**Pull request merged**
