### PR TITLE
Update garbage collection docs (#4552)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #4552 to release-5.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In docs repo:
git pr https://github.com/pingcap/docs/pull/5055
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/docs.git pr/5055:release-5.0-ca331fb386d4
```

---

### First-time contributors' checklist 

- [x] I've signed [**Contributor License Agreement**](https://cla-assistant.io/pingcap/docs) that's required for repo owners to accept my contribution.

### What is changed, added or deleted? (Required)

This updates the docs for https://github.com/pingcap/tidb/pull/21988 (now merged).

21988 still allows the previous methods for updating, but because these changes are not validated, they should not be recommended. Incorrect configuration can lead to strange behaviors.

Partially address #4549 (for backup page mentioned, there are still other pages that need readability improvements)

### Which TiDB version(s) do your changes apply to? (Required)

- [x] master (the latest development version)
- [x] v5.0 (TiDB 5.0 versions)
- [ ] v4.0 (TiDB 4.0 versions)
- [ ] v3.1 (TiDB 3.1 versions)
- [ ] v3.0 (TiDB 3.0 versions)
- [ ] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

- https://github.com/pingcap/tidb/pull/21988

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

### CODE REVIEW

**Comment by yikeke** [comment]
Do we need to merge this PR **after** 5.0 GA is released? @morgo

**Comment by morgo** [comment]
I don't quite understand how the docs branching is being done for 5.0. I thought since tidb created `release-5.0` from `master` last week (abandoning `release-5.0-rc`) that docs would need to do similar, and recreate the `release-5.0` branch.

It looks like PRs are being held (for example: https://github.com/pingcap/docs/pull/5007 ), but I think it's fine to merge and say a change is effective since 5.0 even when 5.0 is not yet released? I have noticed we do this with point releases too (not merge docs related to a 4.0.11 feature until 4.0.11 is released). It increases merge conflicts/management pains to keep the PRs open.

**Comment by yikeke** [comment]
> I don't quite understand how the docs branching is being done for 5.0. I thought since tidb created release-5.0 from master last week (abandoning release-5.0-rc) that docs would need to do similar, and recreate the release-5.0 branch.

I'd like to transfer this conversation to Slack if you don't mind. We can continue our discussion there.

> It looks like PRs are being held (for example: #5007 ), but I think it's fine to merge and say a change is effective since 5.0 even when 5.0 is not yet released? I have noticed we do this with point releases too (not merge docs related to a 4.0.11 feature until 4.0.11 is released). It increases merge conflicts/management pains to keep the PRs open.

`merge and say a change is effective since 5.0 even when 5.0 is not yet released` this one is hard to do. Two reasons: 1. for example #5007, there are small changes in several documents. We can't write a notice for every small change. 2. We want to reduce as many version-specific descriptions as possible on `master`, so we try to avoid a statement like "a change is effective since 5.0". Again, this problem is related to the docs release strategy, we can discuss it in detail on Slack.

**Comment by bb7133** [comment]
Please get me involved, what is the proper time to merge it?

**Comment by yikeke** [comment]
Now is the time to merge. We have aborted the auto-deployment for the release-5.0 branch.

**Review by yikeke — APPROVED** [review]

**Pull request merged**
