### PR TITLE
keywords: add placement into reversed keyword

### PR DESCRIPTION
**Pull request by xhebox**
Signed-off-by: xhe <xw897002528@gmail.com>

### First-time contributors' checklist 

- [x] I've signed [**Contributor License Agreement**](https://cla-assistant.io/pingcap/docs) that's required for repo owners to accept my contribution.

### What is changed, added or deleted? (Required)

It is missed while developing "PLACEMENT RULES IN SQL". It is added as a keyword, because yacc shift/reduce conflict is hard to solve.

### Which TiDB version(s) do your changes apply to? (Required)

**Tips for choosing the affected version(s):**

By default, **CHOOSE MASTER ONLY** so your changes will be applied to the next TiDB major or minor releases. If your PR involves a product feature behavior change or a compatibility change, **CHOOSE THE AFFECTED RELEASE BRANCH(ES) AND MASTER**.

For details, see [tips for choosing the affected versions](https://github.com/pingcap/docs/blob/master/CONTRIBUTING.md#guideline-for-choosing-the-affected-versions).

- [x] master (the latest development version)
- [x] v5.1 (TiDB 5.1 versions)
- [x] v5.0 (TiDB 5.0 versions)
- [ ] v4.0 (TiDB 4.0 versions)
- [ ] v3.1 (TiDB 3.1 versions)
- [ ] v3.0 (TiDB 3.0 versions)
- [ ] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s): pingcap/parser#921

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

### CODE REVIEW

**Comment by dveeden** [comment]
Looks like there are more keywords missing
```
$ for kw in $(awk '/The following tokens belong to ReservedKeyword/ { kw=1 } /The following tokens belong to NotKeywordToken/ { kw=0 } { if ((kw == 1)&&(NF==2)) { print substr($2,2,length($2)-2) }}' parser.y); do egrep "^- $kw($| )" ../docs/keywords.md > /dev/null || echo "Missing keyword: $kw" ; done
Missing keyword: CALL
Missing keyword: FETCH
Missing keyword: INTERSECT
Missing keyword: OF
Missing keyword: PLACEMENT
Missing keyword: RECURSIVE
Missing keyword: STATS_EXTENDED
Missing keyword: TABLESAMPLE
Missing keyword: ATTRIBUTES
Missing keyword: BERNOULLI
Missing keyword: CAUSAL
Missing keyword: CLIENT_ERRORS_SUMMARY
Missing keyword: CONSISTENCY
Missing keyword: CLUSTERED
Missing keyword: HELP
Missing keyword: HISTOGRAM
Missing keyword: LOCKED
Missing keyword: NONCLUSTERED
Missing keyword: OFF
Missing keyword: OPTIONAL
Missing keyword: PERCENT
Missing keyword: POLICY
Missing keyword: PRESERVE
Missing keyword: PROXY
Missing keyword: PURGE
Missing keyword: REPLICAS
Missing keyword: REQUIRED
Missing keyword: RESTART
Missing keyword: RESUME
Missing keyword: SAN
Missing keyword: SKIP
Missing keyword: SYSTEM
Missing keyword: WAIT
```

**Comment by dveeden** [comment]
To make my test a bit more readable:
```sh
for kw in $(awk '
/The following tokens belong to ReservedKeyword/ {
  kw=1
}
/The following tokens belong to NotKeywordToken/ {
  kw=0
}

{
  if ((kw == 1)&&(NF==2)) {
    print substr($2,2,length($2)-2)
  }
}
' parser.y)
do
  egrep "^- $kw($| )" ../docs/keywords.md > /dev/null || echo "Missing keyword: $kw"
done
```

**Comment by dveeden** [comment]
Might be good to reference https://dev.mysql.com/doc/refman/8.0/en/keywords.html and explicitly name reserved keywords that are TiDB Only as that affects MySQL compatibility

**Comment by dveeden** [comment]
Note that MySQL has this:
```
mysql-8.0.26 > TABLE information_schema.KEYWORDS LIMIT 5;
+------------+----------+
| WORD       | RESERVED |
+------------+----------+
| ACCESSIBLE |        1 |
| ACCOUNT    |        0 |
| ACTION     |        0 |
| ACTIVE     |        0 |
| ADD        |        1 |
+------------+----------+
5 rows in set (0.00 sec)
```
https://dev.mysql.com/doc/refman/8.0/en/information-schema-keywords-table.html

**Comment by xhebox** [comment]
Closed, it has opened for so long. And the original problem is actually solved. Problem mentioned by dveeden has been recorded in my TODO list.

**Pull request closed without merging**
