### PR TITLE
reference: add docs for unified read pool configs

### PR DESCRIPTION
**Pull request by sticnarf**
# What is changed, added or deleted? 

Add documentations for the configurations of TiKV's unified read pool.

### What is the related PR or file link(s)? 

- [x] Reference link(s):
- https://github.com/tikv/tikv/pull/6585 adds options to enable this feature.
- https://github.com/tikv/tikv/pull/6593 enables the feature by default.
- https://github.com/tikv/tikv/pull/6597 adds some more options to this feature.
- [ ] This PR is to align with:

- [ ] N/A (not applicable)

### Which TiDB version(s) does your changes apply to? 

- [ ] All active versions: dev, v3.0, v2.1, v3.1
- [x] dev (the latest development version)
- [ ] v3.0 (TiDB 3.0 versions)
- [ ] v2.1 (TiDB 2.1 versions)
- [ ] v3.1 (TiDB 3.1 versions)
- [x] v4.0 (TiDB 4.0 versions)
- [ ] All active and inactive versions
- [ ] N/A (not applicable)

### CODE REVIEW

**Comment by yikeke** [comment]
Please request someone's technical review from your team~ @sticnarf

**Comment by sticnarf** [comment]
PTAL @andylokandy

**Comment by sticnarf** [comment]
PTAL @AndreMouche

**Comment by yikeke** [comment]
Please sign the CLA. @AndreMouche

**Comment by yikeke** [comment]
ping @AndreMouche

**Pull request merged**
