### PR TITLE
Fix typos for .md files at root directory

### PR DESCRIPTION
**Pull request by n0vad3v**
### What is changed, added or deleted? (Required)

Tons of typo fix for .md files at root directory of this repo.

> Some backgrounds on how theses typos are fixed, I've wrote a (Chinese) blog about this: https://nova.moe/fast-typo-fix/ (English version: https://nova.moe/fast-typo-fix-en/) 😇

### Which TiDB version(s) do your changes apply to? (Required)

**Tips for choosing the affected version(s):**

By default, **CHOOSE MASTER ONLY** so your changes will be applied to the next TiDB major or minor releases. If your PR involves a product feature behavior change or a compatibility change, **CHOOSE THE AFFECTED RELEASE BRANCH(ES) AND MASTER**.

For details, see [tips for choosing the affected versions](https://github.com/pingcap/docs/blob/master/CONTRIBUTING.md#guideline-for-choosing-the-affected-versions).

- [x] master (the latest development version)
- [ ] v8.1 (TiDB 8.1 versions)
- [ ] v8.0 (TiDB 8.0 versions)
- [ ] v7.6 (TiDB 7.6 versions)
- [ ] v7.5 (TiDB 7.5 versions)
- [ ] v7.1 (TiDB 7.1 versions)
- [ ] v6.5 (TiDB 6.5 versions)
- [ ] v6.1 (TiDB 6.1 versions)
- [ ] v5.4 (TiDB 5.4 versions)
- [ ] v5.3 (TiDB 5.3 versions)
- [ ] v5.2 (TiDB 5.2 versions)
- [ ] v5.1 (TiDB 5.1 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s):

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

### CODE REVIEW

**Comment by n0vad3v** [comment]
@ti-chi-bot 
> It looks like this is your first PR to [pingcap/docs](https://github.com/pingcap/docs) 🎉.

Nope, I've PR merged before: https://github.com/pingcap/docs/pull/2058, don't you remember? oh, that was the time you're not here.😏

**Comment by qiancai** [comment]
Hi @n0vad3v, thanks very much for your contribution. It seems that most typos in this PR have been fixed in https://github.com/pingcap/docs/pull/17381/files already (actually it was inspired by your brilliant blog https://nova.moe/fast-typo-fix/). Now, I've merged the latest upstream to this PR and there is one typo left in this PR.

**Comment by n0vad3v** [comment]
@qiancai Wow, nice😇 , so should we close this PR for now?

**Review by nolouch — APPROVED** [review]

**Review by qiancai — APPROVED** [review]
LGTM

**Pull request merged**
