### PR TITLE
ci: filter md in linkcheck

### PR DESCRIPTION
**Pull request by ran-huang**
### What is changed, added or deleted? (Required)

fix a bug introduced in https://github.com/pingcap/docs/pull/9862
After this is merged, the link fail fast workflow only checks md files.
If the changed files do not contain a md file, the link check is skipped.

### Which TiDB version(s) do your changes apply to? (Required)

- [x] master (the latest development version)
- [x] v6.2 (TiDB 6.2 versions)
- [x] v6.1 (TiDB 6.1 versions)
- [ ] v5.4 (TiDB 5.4 versions)
- [ ] v5.3 (TiDB 5.3 versions)
- [ ] v5.2 (TiDB 5.2 versions)
- [ ] v5.1 (TiDB 5.1 versions)
- [ ] v5.0 (TiDB 5.0 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s): 

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

### CODE REVIEW

**Comment by ran-huang** [comment]
**Note: remove the img before merge.**

**Review by Oreoxmt — APPROVED** [review]
LGTM

**Pull request merged**
