### PR TITLE
sysvars: add tidb_skip_ascii_check

### PR DESCRIPTION
**Pull request by xhebox**
### First-time contributors' checklist 

- [x] I've signed [**Contributor License Agreement**](https://cla-assistant.io/pingcap/docs) that's required for repo owners to accept my contribution.

### What is changed, added or deleted? (Required)

As title.

### Which TiDB version(s) do your changes apply to? (Required)

- [x] master (the latest development version)
- [x] v5.0 (TiDB 5.0 versions)
- [ ] v4.0 (TiDB 4.0 versions)
- [ ] v3.1 (TiDB 3.1 versions)
- [ ] v3.0 (TiDB 3.0 versions)
- [ ] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5792
- Other reference link(s): https://github.com/pingcap/tidb/pull/18193, the introduction of this variable

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

### CODE REVIEW

**Comment by TomShawn** [comment]
@xhebox From which version this variable is introduced? 5.0 GA?

**Comment by xhebox** [comment]
@TomShawn It was introduced before 5.0, only in master. But now it is a part of the 5.0 GA features. GA needs corresponding documents.

**Comment by TomShawn** [comment]
> @TomShawn It was introduced before 5.0, only in master. But now it is a part of the 5.0 GA features. GA needs corresponding documents.

For the release-5.0 branch, can we say that it is introduced in v5.0.0 RC?

**Comment by xhebox** [comment]
> For the release-5.0 branch, can we say that it is introduced in v5.0.0 RC?

I think we can, the commit of the PR is in 5.0-rc.

**Pull request merged**
