### PR TITLE
[WIP] Proposal to change TOC

### PR DESCRIPTION
**Pull request by morgo**
* Rename Operations Guide to Platform Guide
   - Move Platform related About, Quickstart under
   - Move hardware requirements under Deploy
   - Move Ansible specific content under ansible
   - Move scale, best practices and tikv tuning under "Optimize" heading (all Platform guide sub headings follow natural progress now: deploy, configure, backup, monitor, optimize)
* Add new "components" top level
   - Rename user guide to TiDB Server and move under
      - Move MySQL Compatibility Up in Order
      - Add Extensions to MySQL directly after MySQL Compatibility
   - Move TiKV, TiSpark under
   - Add new PD item
* Remove "More Resources" (only Frequently Used Tools is not mentioned elsewhere)
* Move adoptors, roadmap under platform

### CODE REVIEW

**Comment by gregwebs** [comment]
:+1: rather than "optimize", which is something I generally don't bother with, we could use something more like "operate". Mostly I am thinking of scaling, which is required as your data or queries grow. If you were an optimizer you might put work into optimization and delay your scaling.

**Comment by morgo** [comment]
@gregwebs I chatted with @shenli and moved scaling further up in the TOC.  I agree with you, to scale does not mean optimizing.

**Comment by morgo** [comment]
To discuss:
Add operator under deployment.
Basic SQL statements - can we merge with bikeshare?
For the kubernetes deployment and ansible, should we use tabs in the document (with canonical URLs) rather than separate pages in TOC?

**Comment by morgo** [comment]
Closing for now.  Good discussion topic for the next in-person developer meeting.

**Pull request closed without merging**
