### PR TITLE
sql-statements: add statement reference for ROLES

### LINKED ISSUE #2641: Document Roles syntax in Statement index
## Change Request

**This repository is ONLY used to solve issues related to DOCS.
For other issues (related to TiDB, PD, etc), please move to [other repositories](https://github.com/pingcap/).**

Please answer the following questions before submitting your issue. Thanks!

1. Describe what you find is inappropriate or missing in the existing docs.

The syntax for roles is not in the statement index: https://pingcap.com/docs/stable/sql-statements/sql-statement-drop-user/

2. Describe your suggestion or addition.

```
CREATE ROLE
DROP ROLE
GRANT <role> (split GRANT privileges and GRANT role).
SET DEFAULT ROLE
SET ROLE
etc
```

3. Provide some reference materials (documents, websites, etc) if you could.

### PR DESCRIPTION
**Pull request by nullnotnil**
### What is changed, added or deleted? (Required)

Fixes #2641

The documentation for the statements associated with ROLES (RBAC) is incomplete and missing examples.

### Which TiDB version(s) do your changes apply to? (Required)

- [x] master (the latest development version)
- [x] v4.0 (TiDB 4.0 versions)
- [x] v3.1 (TiDB 3.1 versions)
- [x] v3.0 (TiDB 3.0 versions)
- [ ] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s):

### CODE REVIEW

**Comment by yikeke** [comment]
PTAL @bb7133 @tiancaiamao @zimulala @lilin90

**Comment by bb7133** [comment]
I'm not familiar with 'ROLES'-related statements, @imtbkcat PTAL

**Pull request merged**
