### PR TITLE
Update the title level of Concentrated reads or writes

### PR DESCRIPTION
**Pull request by qiancai**
### What is changed, added or deleted? (Required)

Update the title level of "Concentrated reads or writes" from the 2nd to the 3rd, because its parent title "Common heatmap types" is in the 2nd level.

### Which TiDB version(s) do your changes apply to? (Required)

- [x] master (the latest development version)
- [x] v5.0 (TiDB 5.0 versions)
- [x] v4.0 (TiDB 4.0 versions)
- [ ] v3.1 (TiDB 3.1 versions)
- [ ] v3.0 (TiDB 3.0 versions)
- [ ] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5730
- Other reference link(s):

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

### CODE REVIEW

**Review by CharLotteiu — APPROVED** [review]
LGTM

**Comment by TomShawn** [comment]
@qiancai Please sign the [CLA](https://github.com/pingcap/docs/pull/5039#issuecomment-799174513) for this PR to be merged, thanks!

**Comment by qiancai** [comment]
> @qiancai Please sign the [CLA](https://github.com/pingcap/docs/pull/5039#issuecomment-799174513) for this PR to be merged, thanks!

Done. Thanks for the reminder.

**Comment by qiancai** [comment]
This PR is closed because the CLA is not signed and can only be signed at the first commit.

**Pull request closed without merging**
