### PR TITLE
Correct the sample of Pulsar sink url auth param config.md

### PR DESCRIPTION
**Pull request by Liuxiaozhen12**
### What is changed, added or deleted? (Required)

The sample of Pulsar sink url auth param config is wrong.
### Which TiDB version(s) do your changes apply to? (Required)

- [x] master (the latest development version)
- [x] v5.0 (TiDB 5.0 versions)
- [x] v4.0 (TiDB 4.0 versions)
- [ ] v3.1 (TiDB 3.1 versions)
- [ ] v3.0 (TiDB 3.0 versions)
- [ ] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

- This PR is translated from:https://github.com/pingcap/docs-cn/pull/6026
- Other reference link(s):

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

### CODE REVIEW

**Comment by Liuxiaozhen12** [comment]
/retitle Correct the sample of Pulsar sink url auth param config.md

**Comment by Liuxiaozhen12** [comment]
remove-label needs-cherry-pick-master
/label needs-cherry-pick-5.0

**Review by TomShawn — APPROVED** [review]
LGTM

**Pull request merged**
