### PR TITLE
maintain: update mydumper/loader doc

### PR DESCRIPTION
**Pull request by TomShawn**
### What is changed, added or deleted? 

Remove an inaccurate example and update the recommended value.

### What is the related PR or file link(s)? 

This PR deals with part of https://github.com/pingcap/docs-cn/pull/1838. The other changes in https://github.com/pingcap/docs-cn/pull/1838 will be handled by @juliezhang1112.

### Which version does your change affect? 

dev, v2.1, v3.0, v3.1

### CODE REVIEW

**Comment by WangXiangUSTC** [comment]
LGTM

**Comment by TomShawn** [comment]
@juliezhang1112 The `backup-and-restore.md` has been updated according to [#1838](https://github.com/pingcap/docs-cn/pull/1838).

**Comment by juliezhang1112** [comment]
> #1838

Got it! Thanks~

**Comment by juliezhang1112** [comment]
> @juliezhang1112 The `backup-and-restore.md` has been updated according to [#1838](https://github.com/pingcap/docs-cn/pull/1838).

Got it! Thanks~

**Pull request merged**
