### PR TITLE
dev/how-to/get-started: add supported MySQL versions

### PR DESCRIPTION
**Pull request by CaitinChen**
@kolbe @ericsyh @morgo @queenypingcap @lilin90 PTAL

### CODE REVIEW

**Comment by morgo** [comment]
Can we change this to be versions less than MySQL 8.0?  5.8 was never released - it was a number internally that changed to 8.0 well before release.

**Comment by lilin90** [comment]
> Can we change this to be versions less than MySQL 8.0? 5.8 was never released - it was a number internally that changed to 8.0 well before release.

@csuzhangxc @ericsyh Please take a look at @morgo's comment.

**Comment by csuzhangxc** [comment]
Oh, change it to _8.0_ is better.

**Comment by CaitinChen** [comment]
@ericsyh  @csuzhangxc PTAL again.

**Comment by ericsyh** [comment]
LGTM

**Pull request merged**
