### PR TITLE
tidb-binlog: add decription for initial-commit-ts

### PR DESCRIPTION
**Pull request by Joyinqin**
### What is changed, added or deleted? (Required)
Add description of the 0 value of initial-commit-ts.

### Which TiDB version(s) do your changes apply to? (Required)

- [ ] master (the latest development version)
- [ ] v4.0 (TiDB 4.0 versions)
- [ ] v3.1 (TiDB 3.1 versions)
- [x] v3.0 (TiDB 3.0 versions)
- [x] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/4637
- Other reference link(s):

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Have version specific changes 
- [ ] Might cause conflicts

### CODE REVIEW

**Review by ran-huang — COMMENTED** [review]
LGTM

**Comment by Joyinqin** [comment]
@july2993 PTAL, thanks~

**Review by july2993 — APPROVED** [review]

**Review by ran-huang — APPROVED** [review]

**Pull request merged**
