### PR TITLE
br: update some faq from oncall (#5411)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #5411 to release-4.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In docs repo:
git pr https://github.com/pingcap/docs/pull/5504
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/docs.git pr/5504:release-4.0-897d1ccd274f
```

---

### First-time contributors' checklist 

- [ ] I've signed [**Contributor License Agreement**](https://cla-assistant.io/pingcap/docs) that's required for repo owners to accept my contribution.

### What is changed, added or deleted? (Required)
Update some br docs and add some faq.

### Which TiDB version(s) do your changes apply to? (Required)

- [x] master (the latest development version)
- [x] v5.0 (TiDB 5.0 versions)
- [x] v4.0 (TiDB 4.0 versions)
- [ ] v3.1 (TiDB 3.1 versions)
- [ ] v3.0 (TiDB 3.0 versions)
- [ ] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5663
- Other reference link(s):

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [x] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

### CODE REVIEW

**Comment by CharLotteiu** [comment]
@Joyinqin Please resolve the conflict. Thanks~

**Comment by Joyinqin** [comment]
Addressed. PTAL, thx :) @CharLotteiu

**Comment by CharLotteiu** [comment]
Just notice that this PR requires version-specific changes. Please align it with https://github.com/pingcap/docs-cn/pull/6074/files. @Joyinqin

**Comment by Joyinqin** [comment]
> Just notice that this PR requires version-specific changes. Please align it with https://github.com/pingcap/docs-cn/pull/6074/files. @Joyinqin

Updated~

**Review by CharLotteiu — APPROVED** [review]

**Pull request merged**
