### PR TITLE
scripts: update golang version

### PR DESCRIPTION
**Pull request by YKG**
According to this doc: https://github.com/pingcap/tidb/blob/master/CONTRIBUTING.md#go, we need to upgrade Go to version `1.12`

### CODE REVIEW

**Comment by morgo** [comment]
LGTM, but I suggest that maybe we should remove this file instead -- since I don't think it is linked to from anywhere, and maintaining in two places leads to files getting out of date :(

**Comment by YKG** [comment]
This file used to linked by `dev-guide/requirements.md` when I created this PR. It seems like the `dev-guide` has been removed during the last 2 weeks. Actually this file is useful to me to setup the environment before I can run TiKV/PD/TiDB. I'm sure it does save developers' time and we'd better to keep this file and add a link to this file somewhere.

**Comment by morgo** [comment]
> This file used to linked by `dev-guide/requirements.md` when I created this PR. It seems like the `dev-guide` has been removed during the last 2 weeks. Actually this file is useful to me to setup the environment before I can run TiKV/PD/TiDB. I'm sure it does save developers' time and we'd better to keep this file and add a link to this file somewhere.

I have a couple of questions:
1) Where did you find the link to `dev-guide/requirements.md`? It was not in the Table of Contents.
2) What content was here, that is not in https://github.com/pingcap/tidb/blob/master/CONTRIBUTING.md (and corresponding files for [tikv](https://github.com/tikv/tikv#building--testing) and [pd](https://github.com/pingcap/pd#build)) ?

**Comment by YKG** [comment]
1. You can checkout it by `git checkout 2c2c65f`, or you can visit https://github.com/YKG/docs/tree/master/dev-guide .
2. What I did in this PR is to update the minimum golang version, because in this section https://github.com/pingcap/tidb/blob/master/CONTRIBUTING.md#go it says the minimum version now is `1.12` while the script in the PR was `1.10` which is outdated.

**Comment by lilin90** [comment]
> This file used to linked by `dev-guide/requirements.md` when I created this PR. It seems like the `dev-guide` has been removed during the last 2 weeks. Actually this file is useful to me to setup the environment before I can run TiKV/PD/TiDB. I'm sure it does save developers' time and we'd better to keep this file and add a link to this file somewhere.

@YKG Thanks for your feedback. We'll update the original files and add them back soon.

**Comment by YKG** [comment]
Thanks @lilin90 . I guess the second link you provided should be helpful for developers who only wants to build TiDB. But if someone wants to build TiKV from source, `rust`/`g++`/`gdb` must be installed first, then the script(`scripts/check_requirement.sh`)  in this PR can help him/her to install all of them(except `gdb`, I'm planning to add `gdb` install part but haven't yet).

**Comment by lilin90** [comment]
@YKG I added them back in #1438. PTAL

**Pull request merged**
