### PR TITLE
update doc to match config default value with TiKV codebase. (#5188)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #5188 to release-4.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In docs repo:
git pr https://github.com/pingcap/docs/pull/5219
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/docs.git pr/5219:release-4.0-eeb98c08734c
```

---

### First-time contributors' checklist 

- [ ] I've signed [**Contributor License Agreement**](https://cla-assistant.io/pingcap/docs) that's required for repo owners to accept my contribution.

### What is changed, added or deleted? (Required)
Match TiKV docs's config default value with TiKV codebase.

### Which TiDB version(s) do your changes apply to? (Required)

- [x] master (the latest development version)
- [x] v5.0 (TiDB 5.0 versions)
- [x] v4.0 (TiDB 4.0 versions)
- [ ] v3.1 (TiDB 3.1 versions)
- [ ] v3.0 (TiDB 3.0 versions)
- [ ] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5669
- Other reference link(s):

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

### CODE REVIEW

**Comment by TomShawn** [comment]
@Joyinqin 请根据原 PR cherry-pick 到 release-4.0 分支的 PR 进行修改

**Comment by TomShawn** [comment]
@Joyinqin 不是单纯的解决冲突。请根据 https://github.com/pingcap/docs-cn/pull/5889 进行修改。

**Comment by Joyinqin** [comment]
@TomShawn PTAL again thx~

**Pull request merged**
