### PR TITLE
pessimistic trx: cleanup wording (#3475)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #3475 to release-4.0

---

### What is changed, added or deleted? (Required)

Improve some of the wording in explaining pessimistic transactions.

There were two FAQ items on this page, which relate to the log spam that pessimistic transactions generate. I have a PR for this ( https://github.com/pingcap/tidb/pull/18365 ) -- I am hoping this merges for master, and then the FAQ can be removed from master (but left on v4, v3.1, v3 docs).

This fixes https://github.com/pingcap/tidb/issues/17799

### Which TiDB version(s) do your changes apply to? (Required)

- [x] master (the latest development version)
- [x] v4.0 (TiDB 4.0 versions)
- [x] v3.1 (TiDB 3.1 versions)
- [x] v3.0 (TiDB 3.0 versions)
- [ ] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s):

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Have version specific changes 
- [ ] Might cause conflicts

### CODE REVIEW

**Comment by TomShawn** [comment]
@nullnotnil Why did you delete the FAQ section in `master` while adding it back in `release-4.0`? I think it's better to keep the two branches consistent in this case.

**Comment by nullnotnil** [comment]
This is answered in the description:
> There were two FAQ items on this page, which relate to the log spam that pessimistic transactions generate. I have a PR for this ( pingcap/tidb#18365 ) -- I am hoping this merges for master, and then the FAQ can be removed from master (but left on v4, v3.1, v3 docs).

The PR was not cherry-picked to v4.0.

**Comment by TomShawn** [comment]
> This is answered in the description:
> 
> > There were two FAQ items on this page, which relate to the log spam that pessimistic transactions generate. I have a PR for this ( [pingcap/tidb#18365](https://github.com/pingcap/tidb/pull/18365) ) -- I am hoping this merges for master, and then the FAQ can be removed from master (but left on v4, v3.1, v3 docs).
> 
> The PR was not cherry-picked to v4.0.

Does the FAQ item `The execution time limit for pessimistic transactions.` also relate to the log spam that pessimistic transactions generate? If not, what about adding this one back in `master`?

**Comment by nullnotnil** [comment]
This was merged into the section on `Difference with MySQL InnoDB`. When there was one item left, it didn't make sense to have an FAQ, and works well here.

**Pull request merged**
