### PR TITLE
move retry-limit from configuration into variable

### PR DESCRIPTION
**Pull request by you06**
### What is changed, added or deleted? 

Move `retry-limit` from configuration-file into mysql-variables page

### Which version does your change affect? 

dev and 3.0

### CODE REVIEW

**Comment by you06** [comment]
Oh the lint went wrong on the sections which have no changes in this PR.

**Comment by tiancaiamao** [comment]
LGTM ... what's wrong with the lint?

**Comment by you06** [comment]
@tiancaiamao IDK, there are some problems with markdown code format, how can they pass lint test before? Fix the lint issues will make the doc looks strange :(

**Comment by yikeke** [comment]
FYI: I think the changes in the PR has been merged into the upstream in https://github.com/pingcap/docs/pull/1483. @dcalvin @you06

**Comment by dcalvin** [comment]
Yes no wonder I see no change at all after I merge from the upstream master. Then we can close this PR. @you06

**Comment by you06** [comment]
@yikeke @dcalvin  It is, close this PR.

**Pull request closed without merging**
