### PR TITLE
Remove PITR from BR and Pulsar from Lightning

### PR DESCRIPTION
**Pull request by shichun-0415**
### First-time contributors' checklist 

- [ ] I've signed [**Contributor License Agreement**](https://cla-assistant.io/pingcap/docs) that's required for repo owners to accept my contribution.

### Which TiDB version(s) do your changes apply to? (Required)

**Tips for choosing the affected version(s):**

By default, **CHOOSE MASTER ONLY** so your changes will be applied to the next TiDB major or minor releases. If your PR involves a product feature behavior change or a compatibility change, **CHOOSE THE AFFECTED RELEASE BRANCH(ES) AND MASTER**.

For details, see [tips for choosing the affected versions](https://github.com/pingcap/docs/blob/master/CONTRIBUTING.md#guideline-for-choosing-the-affected-versions).

- [x] master (the latest development version)
- [x] v5.4 (TiDB 5.4 versions)
- [ ] v5.3 (TiDB 5.3 versions)
- [ ] v5.2 (TiDB 5.2 versions)
- [ ] v5.1 (TiDB 5.1 versions)
- [ ] v5.0 (TiDB 5.0 versions)
- [ ] v4.0 (TiDB 4.0 versions)
- [ ] v3.1 (TiDB 3.1 versions)
- [ ] v3.0 (TiDB 3.0 versions)
- [ ] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s): https://github.com/pingcap/docs/pull/5879, https://github.com/pingcap/docs/pull/6190

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

### CODE REVIEW

**Review by TomShawn — APPROVED** [review]

**Review by dveeden — APPROVED** [review]

**Comment by TomShawn** [comment]
@shichun-0415 @dveeden @IANTHEREAL Shall we also delete "cdclog" in https://github.com/shichun-0415/docs/blob/Remove-PITR/ticdc/ticdc-overview.md#sink-support?

**Comment by dveeden** [comment]
> @shichun-0415 @dveeden @IANTHEREAL Shall we also delete "cdclog" in https://github.com/shichun-0415/docs/blob/Remove-PITR/ticdc/ticdc-overview.md#sink-support?

I don't know. iirc the br pitr functionality has been removed, but the cdclog sink might still be there. However the cdclog sink is probably going to be removed as well at some point.

So I think we should keep it for now, but maybe change the text to list it as deprecated instead of experimental. I would also be ok in case people want to remove this. 

In general I think if things are not GA but either experimental, deprecated or otherwise not recommended it should be clearly labeled as such (instead of not being documented at all). Any GA things should be fully documented. Any non-GA things should not require documentation beyond stating that it is not GA, although more documentation (especially for new experimental things) would be good to have.

**Comment by leoppro** [comment]
LGTM

**Pull request merged**
