### PR TITLE
fix wrong version mark

### PR DESCRIPTION
**Pull request by shichun-0415**
### First-time contributors' checklist 

- [ ] I've signed [**Contributor License Agreement**](https://cla-assistant.io/pingcap/docs) that's required for repo owners to accept my contribution.

### Which TiDB version(s) do your changes apply to? (Required)

**Tips for choosing the affected version(s):**

By default, **CHOOSE MASTER ONLY** so your changes will be applied to the next TiDB major or minor releases. If your PR involves a product feature behavior change or a compatibility change, **CHOOSE THE AFFECTED RELEASE BRANCH(ES) AND MASTER**.

For details, see [tips for choosing the affected versions](https://github.com/pingcap/docs/blob/master/CONTRIBUTING.md#guideline-for-choosing-the-affected-versions).

- [x] master (the latest development version)
- [ ] v6.4 (TiDB 6.4 versions)
- [x] v6.3 (TiDB 6.3 versions)
- [x] v6.1 (TiDB 6.1 versions)
- [ ] v5.4 (TiDB 5.4 versions)
- [ ] v5.3 (TiDB 5.3 versions)
- [ ] v5.2 (TiDB 5.2 versions)
- [ ] v5.1 (TiDB 5.1 versions)
- [ ] v5.0 (TiDB 5.0 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s):

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

### CODE REVIEW

**Review by dveeden — COMMENTED** [review]
This fixes only a part of the problem, there are more places where this is a problem.

```
$ git grep -l 'span class="version-mark"'
auto-random.md
br/br-auto-tune.md
pd-configuration-file.md
system-variables.md
ticdc/manage-ticdc.md
tidb-configuration-file.md
tidb-lightning/tidb-lightning-physical-import-mode-usage.md
tikv-configuration-file.md
```

The link on https://docs.pingcap.com/tidb/stable/transaction-overview that links to https://docs.pingcap.com/tidb/stable/system-variables#tidb_enable_1pc-new-in-v50 also doesn't work as the anchor name is `#tidb_enable_1pc-span-classversion-marknew-in-v50span`

**Comment by shichun-0415** [comment]
> there are more places where this is a problem.
@dveeden I will confirm with our FE engineer about this tomorrow. The version-mark format is right and should have directed to the anchor correctly. Maybe there are website-building errors.

**Comment by shichun-0415** [comment]
Hi, @dveeden, we have confirmed with our FE engineer and the website-building does not work as expected. The FE engineer has created a GitHub issue to track this problem https://github.com/pingcap/website-docs/issues/358.

**Comment by shichun-0415** [comment]
> The FE engineer has created a GitHub issue to track this problem [pingcap/website-docs#358](https://github.com/pingcap/website-docs/issues/358).

This issue has been fixed. Now you can see that links in [TiDB Limitations](https://docs.pingcap.com/zh/tidb/dev/tidb-limitations) can direct you to the accurate position of the variables.

**Comment by dveeden** [comment]
That means we can close this PR isn't it?

**Comment by shichun-0415** [comment]
> That means we can close this PR isn't it?

Yes

**Pull request closed without merging**
