### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by qiuyesuifeng**
tiny clean up

### CODE REVIEW

**Comment by siddontang** [comment]
LGTM

But  I think `step[1-5]` should be the sub section of `quick start` /cc @queenypingcap

**Comment by qiuyesuifeng** [comment]
Agreed, this catalogue should be updated later.
But `step[1-5]` should be independent, otherwise the `quick start` is a little complex.

**Comment by queenypingcap** [comment]
A quick start guide or quickstart guide is a short, simple introductory guide. It doesn't need to include the following steps.

**Comment by queenypingcap** [comment]
LGTM.

**Pull request merged**
