### PR TITLE
reference: capitalized sql keywords in mysql-compatibility.md

### PR DESCRIPTION
**Pull request by terror**
### What is changed, added or deleted? (Required)
Capitalized all SQL keywords in the compatibility.md file

### Which TiDB version(s) do your changes apply to? (Required)

- [x] master (the latest development version)
- [x] v4.0 (TiDB 4.0 versions)
- [x] v3.1 (TiDB 3.1 versions)
- [x] v3.0 (TiDB 3.0 versions)
- [x] v2.1 (TiDB 2.1 versions)

`needs-cherry-pick-3.1` label: sre-bot will submit a PR to the `release-3.1` branch.
`needs-cherry-pick-3.0` label: sre-bot will submit a PR to the `release-3.0` branch.
`needs-cherry-pick-2.1` label: sre-bot will submit a PR to the `release-2.1` branch.

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s): closes https://github.com/pingcap/docs/issues/2331

### CODE REVIEW

**Comment by TomShawn** [comment]
@terror Thanks for your contribution!
@bb7133 PTAL

**Comment by ran-huang** [comment]
@terror Hi, Liam. Thanks for your continuous contribution!😃
Would you like to join our [docs-sig channel](https://tidbcommunity.slack.com/messages/sig-docs) on Slack?

**Comment by terror** [comment]
> @terror Hi, Liam. Thanks for your continuous contribution!😃
> Would you like to join our [docs-sig channel](https://tidbcommunity.slack.com/messages/sig-docs) on Slack?

Sure! Shoot me an invite 😄

**Comment by ran-huang** [comment]
> > @terror Hi, Liam. Thanks for your continuous contribution!😃
> > Would you like to join our [docs-sig channel](https://tidbcommunity.slack.com/messages/sig-docs) on Slack?
> 
> Sure! Shoot me an invite 😄

[Welcome to the TiDB community](https://join.slack.com/share/I012DBJPZ0C/B6aYVoiUJLeIF3d1oDIfdB9G/zt-dss9d09w-4joyW1xqahDAIGdK8UNH0g)!

**Pull request merged**
