### PR TITLE
TiKV configuration: defaultcf.titan config should not apply to other CFs

### PR DESCRIPTION
**Pull request by yiwu-arbug**
Signed-off-by: Yi Wu <yiwu@pingcap.com>

### First-time contributors' checklist 

- [x] I've signed [**Contributor License Agreement**](https://cla-assistant.io/pingcap/docs) that's required for repo owners to accept my contribution.

### What is changed, added or deleted? (Required)

Titan only works on the defaultcf. The `rocksdb.defaultcf.titan` configs do not apply to `writecf` and `lockcf`. Fixing it. It looks like the Chinese version doesn't have such mistake.

### Which TiDB version(s) do your changes apply to? (Required)

- [x] master (the latest development version)
- [x] v5.1 (TiDB 5.1 versions)
- [x] v5.0 (TiDB 5.0 versions)
- [ ] v4.0 (TiDB 4.0 versions)
- [ ] v3.1 (TiDB 3.1 versions)
- [ ] v3.0 (TiDB 3.0 versions)
- [ ] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s): https://github.com/pingcap/docs/pull/5746

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

### CODE REVIEW

**Comment by yiwu-arbug** [comment]
+ @tabokie

**Review by tabokie — APPROVED** [review]

**Review by TomShawn — APPROVED** [review]
LGTM

**Comment by TomShawn** [comment]
@yiwu-arbug @tabokie If `rocksdb.writecf.titan` and `rocksdb.lockcf.titan` are removed, these two configs will have no user document. Is that expected?

**Comment by tabokie** [comment]
@TomShawn Yes, we don't encourage using it.

**Pull request merged**
