### PR TITLE
*: init release-8.5 configs

### PR DESCRIPTION
**Pull request by qiancai**
### First-time contributors' checklist 

- [ ] I've signed [**Contributor License Agreement**](https://cla-assistant.io/pingcap/docs) that's required for repo owners to accept my contribution.

### What is changed, added or deleted? (Required)

- Remove all aliases
- Delete the TiDB roadmap file
- Update the link of the roadmap in TOC
- Update the links in the index page to v8.5
- Update GitHub code links from master to release-8.5
- Update the dev links to v8.5 links for dev docs

### Which TiDB version(s) do your changes apply to? (Required)

**Tips for choosing the affected version(s):**

By default, **CHOOSE MASTER ONLY** so your changes will be applied to the next TiDB major or minor releases. If your PR involves a product feature behavior change or a compatibility change, **CHOOSE THE AFFECTED RELEASE BRANCH(ES) AND MASTER**.

For details, see [tips for choosing the affected versions (in Chinese)](https://github.com/pingcap/docs-cn/blob/master/CONTRIBUTING.md#版本选择指南).

- [ ] master (the latest development version)
- [ ] v8.5 (TiDB 8.5 versions)
- [ ] v8.4 (TiDB 8.4 versions)
- [ ] v8.3 (TiDB 8.3 versions)
- [ ] v8.2 (TiDB 8.2 versions)
- [ ] v8.1 (TiDB 8.1 versions)
- [ ] v7.5 (TiDB 7.5 versions)
- [ ] v7.1 (TiDB 7.1 versions)
- [ ] v6.5 (TiDB 6.5 versions)
- [ ] v6.1 (TiDB 6.1 versions)
- [ ] v5.4 (TiDB 5.4 versions)
- [ ] v5.3 (TiDB 5.3 versions)

### What is the related PR or file link(s)?

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/19182
- Other reference link(s):

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch
…ap and support policy

### CODE REVIEW

**Comment by Oreoxmt** [comment]
Should we update the version reference from "dev" to "v8.5" in the following lines?

https://github.com/pingcap/docs/blob/813a2c660b6b76f428feec1d8a899bcc5208b8f9/vector-search-integration-overview.md?plain=1#L59-L77

**Comment by Oreoxmt** [comment]
The version updates of GitHub links in docs-cn (https://github.com/pingcap/docs-cn/pull/19182/commits/7250cf2bf56540c2289bf8687adad965fd4fed44) haven't been synchronized with the English docs.

**Comment by qiancai** [comment]
> Should we update the version reference from "dev" to "v8.5" in the following lines?
> 
> https://github.com/pingcap/docs/blob/813a2c660b6b76f428feec1d8a899bcc5208b8f9/vector-search-integration-overview.md?plain=1#L59-L77

Yes, thanks for the catch. Done in [`9c5e0e5` (#19545)](https://github.com/pingcap/docs/pull/19545/commits/9c5e0e508ab8289c42abf710db378a67fff68755).

**Review by Oreoxmt — APPROVED** [review]
LGTM

**Pull request merged**
