### PR TITLE
dev and v3.0, reference/tools/tikv-control.md: add `\` in front of  `$`

### PR DESCRIPTION
**Pull request by YiniXu9506**
### What is changed, added or deleted? 

Add `\` in front of `$` of a text in code block

### What is the related PR or file link(s)? 

PR #1313 

### Which version does your change affect? 

dev, v3.0

### Checklist 

- [ ] Add a new file to `TOC.md`
- [ ] No Tab spaces anywhere 
- [ ] Leave a blank line both before and after a code block
- [ ] Keep the first level heading consistent with `title` in metadata
- [ ] Use *four* spaces for each level of indentation except that in `TOC.md`

### CODE REVIEW

**Comment by xuechunL** [comment]
@lilin90 @dcalvin PTAL
In order to ensure our website can be updated normally, we have already escaped the $ symbol, please confirm the correctness of this code.

**Comment by lilin90** [comment]
@xuechunL Got it. @dcalvin Please help check whether the code is correct with the `\` character now. Thanks!

**Comment by lilin90** [comment]
@YiniXu9506 I found the PR update info at the bottom of PingCAP website was gone again, and I'm wondering whether it's caused by the `\` character in this PR title.

**Comment by yikeke** [comment]
> @YiniXu9506 I found the PR update info at the bottom of PingCAP website was gone again, and I'm wondering whether it's caused by the `\` character in this PR title. @yikeke Please follow up.

Okay.

**Comment by YiniXu9506** [comment]
@lilin90 @yikeke Has been fixed. Thanks!

**Pull request merged**
