### PR TITLE
CI: fix vale runs

### PR DESCRIPTION
**Pull request by dveeden**
### What is changed, added or deleted? (Required)

See also: https://github.com/errata-ai/vale-action/issues/32

### Which TiDB version(s) do your changes apply to? (Required)

**Tips for choosing the affected version(s):**

By default, **CHOOSE MASTER ONLY** so your changes will be applied to the next TiDB major or minor releases. If your PR involves a product feature behavior change or a compatibility change, **CHOOSE THE AFFECTED RELEASE BRANCH(ES) AND MASTER**.

For details, see [tips for choosing the affected versions](https://github.com/pingcap/docs/blob/master/CONTRIBUTING.md#guideline-for-choosing-the-affected-versions).

- [x] master (the latest development version)
- [ ] v8.2 (TiDB 8.2 versions)
- [ ] v8.1 (TiDB 8.1 versions)
- [ ] v8.0 (TiDB 8.0 versions)
- [ ] v7.6 (TiDB 7.6 versions)
- [ ] v7.5 (TiDB 7.5 versions)
- [ ] v7.1 (TiDB 7.1 versions)
- [ ] v6.5 (TiDB 6.5 versions)
- [ ] v6.1 (TiDB 6.1 versions)
- [ ] v5.4 (TiDB 5.4 versions)
- [ ] v5.3 (TiDB 5.3 versions)
- [ ] v5.2 (TiDB 5.2 versions)
- [ ] v5.1 (TiDB 5.1 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s):

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

### CODE REVIEW

**Comment by dveeden** [comment]
Running vale locally doesn't work for me:
```
$ vale -v
vale version 3.6.0
$ vale .
E100 [vocab] Runtime error

'config/vocabularies/PingCAP' directory does not exist

Execution stopped with code 1.
```

When I comment out the Vocab I get this:
```
$ vale .
E201 Invalid value [/home/dvaneeden/dev/pingcap/docs/styles/PingCAP/Ambiguous.yml:4:1]:

   3  level: suggestion
   4* code: false
   5  ignorecase: true
   6  tokens:

has invalid keys: 'code'

Execution stopped with code 1.
```

When I also comment that out I get real results:
```
$ vale . | tail -1
✖ 461 errors, 0 warnings and 866 suggestions in 1297 files.
```

Is this also needed for the CI job?

**Comment by dveeden** [comment]
I've pushed a second commit with the changes that I need to be able to run vale locally.

This contains:
- Moving the vocab
- Removing `code: false` in `Ambiguous.yml`

**Comment by dveeden** [comment]
This seems to work:
image

**Review by Oreoxmt — APPROVED** [review]

**Pull request merged**
