### PR TITLE
update system-variable for statements-summary and fixes statements

### PR DESCRIPTION
**Pull request by TomShawn**
### What is changed, added or deleted? (Required)

+ Fix statements:
    - hibernate region is disabled on release branch.
    - unified thread pool is no longer experimental long time ago.
+ Add value ranges for some system variables

### Which TiDB version(s) do your changes apply to? (Required)

- [x] master (the latest development version)
- [x] v5.0 (TiDB 5.0 versions)
- [ ] v4.0 (TiDB 4.0 versions)
- [ ] v3.1 (TiDB 3.1 versions)
- [ ] v3.0 (TiDB 3.0 versions)
- [ ] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5952 https://github.com/pingcap/docs-cn/pull/5918
- Other reference link(s):

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [x] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

### CODE REVIEW

**Comment by BusyJay** [comment]
Note the default value of hibernate-region is true in master and false in release-5.0.

**Comment by TomShawn** [comment]
> Note the default value of hibernate-region is true in master and false in release-5.0.

Of course. I keep that in mind~

**Pull request merged**
